
// ═══════════════════════════════════════ DATA ═══════════════════════════════════════

// ANIMALS: [group, name, tracked(1/0), killed, skinned, studied]
const AN = [
  ['ALLIGATORS','American Alligator',1,1,1,1],
  ['ALLIGATORS','American Alligator (Small)',1,1,1,1],
  ['ARMADILLO','Nine-Banded Armadillo',1,1,1,1],
  ['BADGER','American Badger',1,1,1,1],
  ['BAT','Little Brown Bat',1,1,1,1],
  ['BEARS','American Black Bear',1,1,1,1],
  ['BEARS','Grizzly Bear',1,1,1,1],
  ['BEAVER','North American Beaver',1,1,1,1],
  ['BLUE JAY','Blue Jay',0,1,1,1],
  ['BOAR','Wild Boar',1,1,1,1],
  ['DEER','Whitetail Buck',1,1,1,1],
  ['DEER','Whitetail Deer',1,1,1,1],
  ['BISON','American Bison',1,1,1,1],
  ['BULLS','Angus Bull',0,0,0,1],
  ['BULLS','Devon Bull',0,0,0,1],
  ['BULLS','Hereford Bull',0,0,0,1],
  ['BULLFROG','American Bullfrog',1,1,1,1],
  ['CARDINAL','Northern Cardinal',0,1,1,1],
  ['CAT','American Domestic Cat',0,0,0,1],
  ['WAXWING','Cedar Waxwing',0,1,1,1],
  ['CHICKENS','Dominique Chicken',0,0,0,1],
  ['CHICKENS','Dominique Rooster',0,0,0,1],
  ['CHICKENS','Java Chicken',0,0,0,1],
  ['CHICKENS','Java Rooster',0,0,0,1],
  ['CHICKENS','Leghorn Chicken',0,0,0,1],
  ['CHICKENS','Leghorn Rooster',0,0,0,1],
  ['CHICKENS','Greater Prairie Chicken',0,0,0,1],
  ['CHIPMUNK','Western Chipmunk',1,1,1,1],
  ['CONDOR','Californian Condor',0,1,1,1],
  ['COUGAR','Cougar',1,1,1,1],
  ['CORMORANT','Double-Crested Cormorant',0,1,1,1],
  ['CORMORANT','Neotropic Cormorant',0,1,1,1],
  ['COW','Florida Cracker Cow',0,0,0,1],
  ['COYOTE','California Valley Coyote',1,1,1,1],
  ['CRAB','Cuban Land Crab',1,1,1,1],
  ['CRAYFISH','Red Swamp Crayfish',0,0,1,1],
  ['CRANES','Whooping Crane',0,1,1,1],
  ['CRANES','Sandhill Crane',0,1,1,1],
  ['CROW','American Crow',0,1,1,1],
  ['DOGS','American Fox Hound',0,0,0,1],
  ['DOGS','Australian Shepherd',0,0,0,1],
  ['DOGS','Bloodhound',0,0,0,1],
  ['DOGS','Bluetick Coonhound',0,0,0,1],
  ['DOGS','Border Collie',0,0,0,1],
  ['DOGS','Catahoula Cur',0,0,0,1],
  ['DOGS','Chesapeake Bay Retriever',0,0,0,1],
  ['DOGS','Siberian Husky',0,0,0,1],
  ['DOGS','Labrador Retriever',0,0,0,1],
  ['DOGS','Poodle',0,0,0,1],
  ['DOGS','Mutt',0,0,0,1],
  ['DOGS','Rufus',0,0,0,1],
  ['DONKEY','Standard Donkey',0,0,0,1],
  ['DUCKS','Mallard Duck',0,1,1,1],
  ['DUCKS','Pekin Duck',0,1,1,1],
  ['EAGLES','Bald Eagle',0,1,1,1],
  ['EAGLES','Golden Eagle',0,1,1,1],
  ['EGRETS','Reddish Egret',0,1,1,1],
  ['EGRETS','Little Egret',0,1,1,1],
  ['EGRETS','Snowy Egret',0,1,1,1],
  ['ELKS','Rocky Mountain Bull Elk',1,1,1,1],
  ['ELKS','Rocky Mountain Cow Elk',1,1,1,1],
  ['FOXES','American Red Fox',1,1,1,1],
  ['FOXES','American Gray Fox',1,1,1,1],
  ['FOXES','Silver Fox',1,1,1,1],
  ['GILA MONSTER','Banded Gila Monster',1,1,1,1],
  ['GOATS','Alpine Goat',0,0,0,1],
  ['GOOSE','Canada Goose',0,1,1,1],
  ['HAWKS','Ferruginous Hawk',0,1,1,1],
  ['HAWKS','Red-Tailed Hawk',0,1,1,1],
  ['HAWKS','Rough-Legged Hawk',0,1,1,1],
  ['HERON','Great Blue Heron',0,1,1,1],
  ['HERON','Tricolored Heron',0,1,1,1],
  ['IGUANA','Desert Iguana',1,1,1,1],
  ['IGUANA','Green Iguana',1,1,1,1],
  ['PECCARY','Collared Peccary',1,1,1,1],
  ['LOONS','Common Loon',0,1,1,1],
  ['LOONS','Pacific Loon',0,1,1,1],
  ['LOONS','Yellow-Billed Loon',0,1,1,1],
  ['MOOSE','Western Bull Moose',1,1,1,1],
  ['MOOSE','Western Moose',1,1,1,1],
  ['MULE','Mule',0,0,0,1],
  ['MUSKRAT','American Muskrat',1,1,1,1],
  ['ORIOLES','Baltimore Oriole',0,1,1,1],
  ['ORIOLES','Hooded Oriole',0,1,1,1],
  ['OWLS','Californian Horned Owl',0,1,1,1],
  ['OWLS','Coastal Horned Owl',0,1,1,1],
  ['OWLS','Great Horned Owl',0,1,1,1],
  ['OXEN','Angus Ox',0,0,0,1],
  ['OXEN','Devon Ox',0,0,0,1],
  ['PANTHERS','Panther',1,1,1,1],
  ['PANTHERS','Florida Panther',1,1,1,1],
  ['PARAKEET','Carolina Parakeet',0,1,1,1],
  ['PARROTS','Blue & Yellow Macaw',0,1,1,1],
  ['PARROTS','Great Green Macaw',0,1,1,1],
  ['PARROTS','Scarlet Macaw',0,1,1,1],
  ['PELICANS','American White Pelican',0,1,1,1],
  ['PELICANS','Brown Pelican',0,1,1,1],
  ['PHEASANTS','Ring-Necked Pheasant',0,1,1,1],
  ['PHEASANTS','Chinese Ring-Necked Pheasant',0,1,1,1],
  ['PIGS','Berkshire Pig',0,0,0,1],
  ['PIGS','Big China Pig',0,0,0,1],
  ['PIGS','Old Spot Pig',0,0,0,1],
  ['PIGEONS','Band-Tailed Pigeon',0,1,1,1],
  ['PIGEONS','Rock Pigeon',0,1,1,1],
  ['OPOSSUM','Virginia Opossum',1,1,1,1],
  ['PRONGHORNS','American Pronghorn Buck',1,1,1,1],
  ['PRONGHORNS','American Pronghorn Doe',1,1,1,1],
  ['PRONGHORNS','Sonoran Pronghorn Buck',1,1,1,1],
  ['PRONGHORNS','Sonoran Pronghorn Doe',1,1,1,1],
  ['PRONGHORNS','Baja California Pronghorn Buck',1,1,1,1],
  ['PRONGHORNS','Baja California Pronghorn Doe',1,1,1,1],
  ['QUAIL','California Quail',1,1,1,1],
  ['RAMS','Sierra Nevada Bighorn Ram',1,1,1,1],
  ['RAMS','Sierra Nevada Bighorn Sheep',1,1,1,1],
  ['RAMS','Desert Bighorn Ram',1,1,1,1],
  ['RAMS','Desert Bighorn Sheep',1,1,1,1],
  ['RAMS','Rocky Mountain Bighorn Ram',1,1,1,1],
  ['RAMS','Rocky Mountain Bighorn Sheep',1,1,1,1],
  ['JACKRABBIT','Black-Tailed Jackrabbit',1,1,1,1],
  ['RACCOON','Common Raccoon',1,1,1,1],
  ['RATS','Black Rat',1,1,1,1],
  ['RATS','Brown Rat',1,1,1,1],
  ['RAVEN','Western Raven',0,1,1,1],
  ['BOOBY','Red-Footed Booby',0,1,1,1],
  ['ROBIN','American Robin',0,1,1,1],
  ['SPOONBILL','Roseate Spoonbill',0,1,1,1],
  ['SEAGULLS','Herring Gull',0,1,1,1],
  ['SEAGULLS','Laughing Gull',0,1,1,1],
  ['SEAGULLS','Ring-Billed Gull',0,1,1,1],
  ['SHEEP','Domestic Sheep',0,0,0,1],
  ['SKUNK','Striped Skunk',1,1,1,1],
  ['SNAKES','Red Boa Snake',1,1,1,1],
  ['SNAKES','Rainbow Boa Snake',1,1,1,1],
  ['SNAKES','Sunglow Boa Snake',1,1,1,1],
  ['SNAKES','Diamondback Rattlesnake',1,1,1,1],
  ['SNAKES','Fer-de-Lance Snake',1,1,1,1],
  ['SNAKES','Black-Tailed Rattlesnake',1,1,1,1],
  ['SNAKES','Timber Rattlesnake',1,1,1,1],
  ['SNAKES','Northern Copperhead Snake',1,1,1,1],
  ['SNAKES','Southern Copperhead Snake',1,1,1,1],
  ['SNAKES','Midland Water Snake',1,1,1,1],
  ['SNAKES','Cottonmouth Snake',1,1,1,1],
  ['SNAKES','Northern Water Snake',1,1,1,1],
  ['SONGBIRDS','Scarlet Tanager Songbird',0,1,1,1],
  ['SONGBIRDS','Western Tanager Songbird',0,1,1,1],
  ['SPARROWS','Eurasian Tree Sparrow',0,1,1,1],
  ['SPARROWS','American Tree Sparrow',0,1,1,1],
  ['SPARROWS','Golden Crowned Sparrow',0,1,1,1],
  ['SQUIRRELS','American Red Squirrel',1,1,1,1],
  ['SQUIRRELS','Western Grey Squirrel',1,1,1,1],
  ['SQUIRRELS','Black Squirrel',1,1,1,1],
  ['TOADS','Western Toad',1,1,1,1],
  ['TOADS','Sonoran Desert Toad',1,1,1,1],
  ['TURKEYS','Eastern Wild Turkey',0,1,1,1],
  ['TURKEYS','Rio Grande Wild Turkey',0,1,1,1],
  ['TURTLE','Alligator Snapping Turtle',1,1,1,1],
  ['VULTURES','Eastern Turkey Vulture',0,1,1,1],
  ['VULTURES','Western Turkey Vulture',0,1,1,1],
  ['WOLVES','Gray Wolf',1,1,1,1],
  ['WOLVES','Timber Wolf',1,1,1,1],
  ['WOODPECKERS','Red-Bellied Woodpecker',0,1,1,1],
  ['WOODPECKERS','Pileated Woodpecker',0,1,1,1],
  ['LEGENDARY','Legendary Alligator',1,1,1,1],
  ['LEGENDARY','Legendary Bear',1,1,1,1],
  ['LEGENDARY','Legendary Beaver',1,1,1,1],
  ['LEGENDARY','Legendary Bison',1,1,1,1],
  ['LEGENDARY','Legendary Boar',1,1,1,1],
  ['LEGENDARY','Legendary Buck',1,1,1,1],
  ['LEGENDARY','Legendary Cougar',1,1,1,1],
  ['LEGENDARY','Legendary Coyote',1,1,1,1],
  ['LEGENDARY','Legendary Elk',1,1,1,1],
  ['LEGENDARY','Legendary Fox',1,1,1,1],
  ['LEGENDARY','Legendary Moose',1,1,1,1],
  ['LEGENDARY','Legendary Panther',1,1,1,1],
  ['LEGENDARY','Legendary Pronghorn',1,1,1,1],
  ['LEGENDARY','Legendary Ram',1,1,1,1],
  ['LEGENDARY','Legendary White Bison',1,1,1,1],
  ['LEGENDARY','Legendary Wolf',1,1,1,1],
];
const AN_COLS = ['TRACKED','KILLED','SKINNED','STUDIED'];

// PLANTS: [cat, name, picked, recipe, herbalist]
// orchids: recipe=0 (no recipe column)
const PL = [
  
  
  ['BERRY','Blackberry',1,1,1],
  ['BERRY','Evergreen Huckleberry',1,1,1],
  ['BERRY','Red Raspberry',1,1,1],
  ['BERRY','Wintergreen Berry',1,1,1],
  ['CURRANT','Golden Currant',1,1,1],
  ['CURRANT','Black Currant',1,1,1],
  ['FLOWER','Prairie Poppy',1,1,1],
  ['FLOWER','Vanilla Flower',1,1,1],
  ['FLOWER','Violet Snowdrops',1,1,1],
  ['GINSENG','Alaskan Ginseng',1,1,1],
  ['GINSENG','American Ginseng',1,1,1],
  ['GRASS','Common Bulrush',1,1,1],
  ['HERB','Creeping Thyme',1,1,1],
  ['HERB','English Mace',1,1,1],
  ['HERB','Indian Tobacco',1,1,1],
  ['HERB','Milkweed',1,1,1],
  ['HERB','Oregano',1,1,1],
  ['HERB','Wild Feverfew',1,1,1],
  ['HERB','Wild Mint',1,1,1],
  ['HERB','Yarrow',1,1,1],
  ['MUSHROOM','Bay Bolete',1,1,1],
  ['MUSHROOM','Chanterelles',1,1,1],
  ['MUSHROOM','Parasol Mushroom',1,1,1],
  ['MUSHROOM',"Ram's Head",1,1,1],
  ['ROOT','Burdock Root',1,1,1],
  ['ROOT','Wild Carrot',1,1,1],
  ['SAGE','Desert Sage',1,1,1],
  ['SAGE','Hummingbird Sage',1,1,1],
  ['SAGE','Oleander Sage',1,1,1],
  ['SAGE','Red Sage',1,1,1],
  
  // Orchids: picked=1, recipe=0 (none), herbalist=1
  ['ORCHID',"Acuna's Star Orchid",1,0,1],
  ['ORCHID','Cigar Orchid',1,0,1],
  ['ORCHID','Clamshell Orchid',1,0,1],
  ['ORCHID',"Dragon's Mouth Orchid",1,0,1],
  ['ORCHID','Ghost Orchid',1,0,1],
  ['ORCHID','Lady of the Night Orchid',1,0,1],
  ['ORCHID','Lady Slipper Orchid',1,0,1],
  ['ORCHID','Moccasin Flower Orchid',1,0,1],
  ['ORCHID','Night Scented Orchid',1,0,1],
  ["ORCHID","Queen's Orchid",1,0,1],
  ['ORCHID','Rat Tail Orchid',1,0,1],
  ["ORCHID","Sparrow's Egg Orchid",1,0,1],
  ['ORCHID','Spider Orchid',1,0,1],
];
const PL_COLS = ['PICKED','RECIPE','HERBALIST'];

// FISH: [name, isLegendary]  — only CAUGHT tracked
const FI = [
  ['Bluegill',0],['Chain Pickerel',0],['Redfin Pickerel',0],
  ['Rock Bass',0],['Smallmouth Bass',0],['Bullhead Catfish',0],
  ['Perch',0],['Lake Sturgeon',0],['Largemouth Bass',0],
  ['Steelhead Trout',0],['Channel Catfish',0],['Longnose Gar',0],
  ['Muskie',0],['Northern Pike',0],['Sockeye Salmon',0],
  ['Legendary Bluegill',1],['Legendary Chain Pickerel',1],
  ['Legendary Bullhead Catfish',1],['Legendary Redfin Pickerel',1],
  ['Legendary Rock Bass',1],['Legendary Smallmouth Bass',1],
  ['Legendary Perch',1],['Legendary Lake Sturgeon',1],
  ['Legendary Largemouth Bass',1],['Legendary Steelhead Trout',1],
  ['Legendary Channel Catfish',1],['Legendary Longnose Gar',1],
  ['Legendary Muskie',1],['Legendary Northern Pike',1],
  ['Legendary Sockeye Salmon',1],
];

// HORSES: [breed, coat, type, location, hasHorseman]
// All coats track Studied / Bonded / Ridden (indices 0-2 in the mc row)
// hasHorseman=1 marks the first coat of breeds that count for the Horseman challenge
const HO = [
  ['AMERICAN PAINT','Grey Overo','Work','Tumbleweed Stable',1],
  ['AMERICAN PAINT','Overo','Work','Stolen / Found',0],
  ['AMERICAN PAINT','Splashed White','Work','Stolen / Found',0],
  ['AMERICAN PAINT','Tobiano','Work','Stolen / Found',0],
  ['AMERICAN STANDARDBRED','Palomino Dapple','Race','Valentine Stable',1],
  ['AMERICAN STANDARDBRED','Silver Tail Buckskin','Race','Tumbleweed Stable',0],
  ['AMERICAN STANDARDBRED','Black','Race','Stolen / Found',0],
  ['AMERICAN STANDARDBRED','Buckskin','Race','Stolen / Found',0],
  ['ANDALUSIAN','Dark Bay','War','Strawberry Stable',0],
  ['ANDALUSIAN','Rose Grey','War','Van Horn Stable',0],
  ['ANDALUSIAN','Perlino','War','Stolen / Found',0],
  ['APPALOOSA','Leopard','Work','Van Horn Stable',1],
  ['APPALOOSA','Brown Leopard','Work','Tumbleweed Stable',0],
  ['APPALOOSA','Blanket','Work','Stolen / Found',0],
  ['APPALOOSA','Leopard Blanket','Work','Stolen / Found',0],
  ['APPALOOSA','Few Spots','Work','Stolen / Found',0],
  ['ARABIAN','Red Chestnut','Superior','Stolen / Found',0],
  ['ARABIAN','Rose Grey Bay','Superior','Blackwater Stable',0],
  ['ARABIAN','Black','Superior','Saint Denis Stable',0],
  ['ARABIAN','White','Superior','Stolen / Found',0],
  ['ARABIAN','Warped Brindle','Superior','Stolen / Found',0],
  ['ARDENNES','Iron Grey','War','Valentine Stable',0],
  ['ARDENNES','Bay Roan','War','Scarlett Meadows Stable',0],
  ['ARDENNES','Strawberry Roan','War','Van Horn Stable',0],
  ['BELGIAN','Mealy Chestnut','Draft','Stolen / Found',0],
  ['BELGIAN','Blonde Chestnut','Draft','Stolen / Found',0],
  ['DUTCH WARMBLOOD','Sooty Buckskin','Multi','Scarlett Meadows Stable',0],
  ['DUTCH WARMBLOOD','Chocolate Roan','Work','Valentine Stable',0],
  ['DUTCH WARMBLOOD','Seal Brown','Work','Strawberry Stable',0],
  ['DUTCH WARMBLOOD','Cremello Gold','Work','Buell (Special)',0],
  ['HUNGARIAN HALFBRED','Dapple Dark Grey','War','Valentine Stable',1],
  ['HUNGARIAN HALFBRED','Piebald Tobiano','War','Stolen / Found',0],
  ['HUNGARIAN HALFBRED','Flaxen Chestnut','War','Stolen / Found',0],
  ['KENTUCKY SADDLER','Grey','Riding','Valentine Stable / Stolen',1],
  ['KENTUCKY SADDLER','Chestnut Pinto','Riding','Stolen / Found',0],
  ['KENTUCKY SADDLER','Black','Riding','Stolen / Found',0],
  ['KENTUCKY SADDLER','Silver Bay','Riding','Stolen / Found',0],
  ['KENTUCKY SADDLER','Buttermilk Buckskin','Riding','Stolen / Found',0],
  ['MISSOURI FOX TROTTER','Amber Champagne','Multi','Scarlett Meadows Stable',0],
  ['MISSOURI FOX TROTTER','Silver Dapple Pinto','Multi','Blackwater Stable',0],
  ['MORGAN','Palomino','Riding','Valentine Stable / Stolen',1],
  ['MORGAN','Bay Roan','Riding','Valentine Stable / Stolen',0],
  ['MORGAN','Bay','Riding','Stolen / Found',0],
  ['MORGAN','Flaxen Chestnut','Riding','Stolen / Found',0],
  ['MORGAN','Liver Chestnut','Riding','Stolen / Found',0],
  ['MUSTANG','Tiger Striped Bay','Multi','Stolen / Found',1],
  ['MUSTANG','Grullo Dun','Multi','Stolen / Found',0],
  ['MUSTANG','Wild Bay','Multi','Stolen / Found',0],
  ['NOKOTA','Reverse Dapple Roan','Race','Saint Denis Stable',1],
  ['NOKOTA','Blue Roan','Race','Stolen / Found',0],
  ['NOKOTA','White Roan','Race','Stolen / Found',0],
  ['SHIRE','Raven Black','Draft','Bonus Reward',0],
  ['SHIRE','Light Grey','Draft','Stolen / Found',0],
  ['SHIRE','Dark Bay','Draft','Stolen / Found',0],
  ['SUFFOLK PUNCH','Sorrel','Draft','Stolen / Found',0],
  ['SUFFOLK PUNCH','Red Chestnut','Draft','Stolen / Found',0],
  ['TENNESSEE WALKER','Mahogany Bay','Riding',"Arthur's Horse",1],
  ['TENNESSEE WALKER','Red Roan','Riding','Valentine Stable / Stolen',0],
  ['TENNESSEE WALKER','Flaxen Roan','Riding','Tumbleweed Stable',0],
  ['TENNESSEE WALKER','Black Rabicano','Riding','Stolen / Found',0],
  ['TENNESSEE WALKER','Dapple Bay','Riding','Stolen / Found',0],
  ['TENNESSEE WALKER','Chestnut','Riding','Stolen / Found',0],
  ['TENNESSEE WALKER','Gold Palomino','Riding','Stolen / Found',0],
  ['THOROUGHBRED','Dappled Black','Race','Strawberry Stable',0],
  ['THOROUGHBRED','Brindle','Race','Stolen / Found',0],
  ['THOROUGHBRED','Blood Bay','Race','Stolen / Found',0],
  ['THOROUGHBRED','Dapple Grey','Race','Stolen / Found',0],
  ['THOROUGHBRED','Seal Brown','Race',"Rachel — John's Horse",0],
  ['TURKOMAN','Gold','Multi','Saint Denis Stable',0],
  ['TURKOMAN','Dark Bay','Multi','Blackwater Stable',0],
  ['TURKOMAN','Silver','Multi','Tumbleweed Stable',0],
];
const HO_COLS = ['STUDIED','BONDED','RIDDEN'];

// WEAPONS: [category, name]
const WE = [
  ['REVOLVERS','Cattleman Revolver'],['REVOLVERS',"Granger's Revolver"],['REVOLVERS',"Flaco's Revolver"],
  ['REVOLVERS',"John's Cattleman Revolver"],['REVOLVERS','Double-Action Revolver'],['REVOLVERS',"Algernon's Revolver"],
  ['REVOLVERS',"Micah's Revolver"],['REVOLVERS','High Roller Revolver'],['REVOLVERS','Schofield Revolver'],
  ['REVOLVERS',"Calloway's Revolver"],['REVOLVERS',"Otis Miller's Revolver"],['REVOLVERS','LeMat Revolver'],
  ['PISTOLS','Volcanic Pistol'],['PISTOLS','Semi-Automatic Pistol'],['PISTOLS','Mauser Pistol'],
  ['PISTOLS',"Midnight's Pistol"],['PISTOLS','M1899 Pistol'],
  ['REPEATERS','Carbine Repeater'],['REPEATERS','Lancaster Repeater'],['REPEATERS','Litchfield Repeater'],['REPEATERS','Evans Repeater'],
  ['RIFLES','Varmint Rifle'],['RIFLES','Springfield Rifle'],['RIFLES','Bolt Action Rifle'],
  ['RIFLES','Rolling Block Rifle'],['RIFLES','Rare Rolling Block Rifle'],['RIFLES','Carcano Rifle'],
  ['SHOTGUNS','Sawed-Off Shotgun'],['SHOTGUNS','Double-Barreled Shotgun'],['SHOTGUNS','Rare Shotgun'],
  ['SHOTGUNS','Pump-Action Shotgun'],['SHOTGUNS','Semi-Auto Shotgun'],['SHOTGUNS','Repeating Shotgun'],
  ['BOW','Bow'],['UNARMED','Unarmed'],
  ['THROWABLES','Fire Bottle'],['THROWABLES','Volatile Fire Bottle'],['THROWABLES','Dynamite'],
  ['THROWABLES','Volatile Dynamite'],['THROWABLES','Throwing Knife'],['THROWABLES','Improved Throwing Knife'],
  ['THROWABLES','Poison Throwing Knife'],['THROWABLES','Tomahawk'],['THROWABLES','Improved Tomahawk'],
  ['THROWABLES','Homing Tomahawk'],['THROWABLES','Ancient Tomahawk'],
  ['MELEE','Cleaver'],['MELEE','Machete'],['MELEE','Broken Pirate Sword'],['MELEE','Hunting Knife'],
  ['MELEE',"John's Knife"],['MELEE','Antler Knife'],['MELEE','Civil War Knife'],['MELEE','Jawbone Knife'],
  ['MELEE','Wide-Blade Knife'],['MELEE','Ornate Dagger'],['MELEE','Hatchet'],['MELEE','Hewing Hatchet'],['MELEE','Viking Hatchet'],
];

// EQUIPMENT: [cat, name, note]
const EQ = [
  ['KIT','Lasso','auto-given'],['KIT','Binoculars','auto-given'],['KIT','Fishing Rod','auto-given'],
  ['KIT','Electric Lantern','"A Bright Bouncing Boy II"'],['KIT','Lantern','auto-given'],['KIT','Camera','auto-given'],
  ['GUN EQUIP','Upgraded Bandolier','purchase at gunsmith'],['GUN EQUIP','Upgraded Gun Belt','purchase at gunsmith'],
  ['GUN EQUIP','Upgraded Holster','purchase at gunsmith'],['GUN EQUIP','Off-Hand Holster','"Blessed Are The Meek?"'],
  ['TALISMANS','Alligator Tooth Talisman','Civil War handcuffs + gold jointed bracelet + Legendary Alligator tooth'],
  ['TALISMANS','Boar Tusk Talisman','gold earring + cobalt petrified wood + Legendary Boar tusk'],
  ['TALISMANS','Bison Horn Talisman','abalone shell fragment + silver earring + Legendary Bison horn'],
  ['TALISMANS','Bear Claw Talisman','silver chain bracelet + quartz chunk + Legendary Bear claw'],
  ['TRINKETS','Tatanka Bison Horn Trinket','Legendary Tatanka Bison horn'],
  ['TRINKETS','Beaver Tooth Trinket','Legendary Beaver tooth'],
  ['TRINKETS','Buck Antler Trinket','Legendary Buck antler'],
  ['TRINKETS','Cougar Fang Trinket','Legendary Cougar fang'],
  ['TRINKETS','Coyote Fang Trinket','Legendary Coyote fang'],
  ['TRINKETS','Elk Antler Trinket','Legendary Elk antler'],
  ['TRINKETS','Fox Claw Trinket','Legendary Fox claw'],
  ['TRINKETS','Moose Antler Trinket','Legendary Moose antler'],
  ['TRINKETS','Owl Feather Trinket','"Archeology for Beginners" — no-kill reward'],
  ['TRINKETS','Pronghorn Horn Trinket','Legendary Pronghorn horn'],
  ['TRINKETS','Ram Horn Trinket','Legendary Ram horn'],
  ['TRINKETS','Raven Claw Talisman','old brass compass'],
  ['TRINKETS','Wolf Heart Trinket','Legendary Wolf heart'],
  ["TRINKETS","Lion's Paw Trinket",'"He\'s British, Of Course IV"'],
  ["TRINKETS","Panther's Eye Trinket",'Legendary Panther eye'],
  ['TRINKETS','Shark Tooth Trinket','Roanoke Ridge — lockbox near beached ship'],
  ['TRINKETS','Hawk Talon Trinket','Deadboot Creek — lockbox at destroyed campsite'],
  ['TRINKETS','Cat Eye Trinket','Flat Iron Lake southern island — lockbox'],
  ['TRINKETS','Turtle Shell Trinket','Gaptooth Breach — lockbox under stairs'],
  ['TRINKETS','Crow Beak Trinket','"Elemental Trails" treasure hunt'],
  ['BANDIT GEAR','Bandit Bandolier','Bandit 1'],
  ['BANDIT GEAR','Bandit Holster','Bandit 3'],
  ['BANDIT GEAR','Bandit Off-Hand Holster','Bandit 7'],
  ['BANDIT GEAR','Bandit Gun Belt','Bandit 10'],
  ['EXPLORER GEAR','Explorer Holster','Explorer 1'],
  ['EXPLORER GEAR','Explorer Bandolier','Explorer 3'],
  ['EXPLORER GEAR','Explorer Gun Belt','Explorer 7'],
  ['EXPLORER GEAR','Explorer Off-Hand Holster','Explorer 10'],
  ['GAMBLER GEAR','Gambler Holster','Gambler 1'],
  ['GAMBLER GEAR','Gambler Bandolier','Gambler 3'],
  ['GAMBLER GEAR','Gambler Gun Belt','Gambler 7'],
  ['GAMBLER GEAR','Gambler Off-Hand Holster','Gambler 10'],
  ['HERBALIST GEAR','Herbalist Off-Hand Holster','Herbalist 1'],
  ['HERBALIST GEAR','Herbalist Gun Belt','Herbalist 3'],
  ['HERBALIST GEAR','Herbalist Holster','Herbalist 7'],
  ['HERBALIST GEAR','Herbalist Bandolier','Herbalist 10'],
  ['HORSEMAN GEAR','Horseman Gun Belt','Horseman 1'],
  ['HORSEMAN GEAR','Horseman Holster','Horseman 3'],
  ['HORSEMAN GEAR','Horseman Bandolier','Horseman 7'],
  ['HORSEMAN GEAR','Horseman Off-Hand Holster','Horseman 10'],
  ['MASTER HUNTER GEAR','Master Hunter Off-Hand Holster','Master Hunter 1'],
  ['MASTER HUNTER GEAR','Master Hunter Bandolier','Master Hunter 3'],
  ['MASTER HUNTER GEAR','Master Hunter Gun Belt','Master Hunter 7'],
  ['MASTER HUNTER GEAR','Master Hunter Holster','Master Hunter 10'],
  ['SHARPSHOOTER GEAR','Sharpshooter Off-Hand Holster','Sharpshooter 1'],
  ['SHARPSHOOTER GEAR','Sharpshooter Bandolier','Sharpshooter 3'],
  ['SHARPSHOOTER GEAR','Sharpshooter Gun Belt','Sharpshooter 7'],
  ['SHARPSHOOTER GEAR','Sharpshooter Holster','Sharpshooter 10'],
  ['SURVIVALIST GEAR','Survivalist Off-Hand Holster','Survivalist 1'],
  ['SURVIVALIST GEAR','Survivalist Bandolier','Survivalist 3'],
  ['SURVIVALIST GEAR','Survivalist Gun Belt','Survivalist 7'],
  ['SURVIVALIST GEAR','Survivalist Holster','Survivalist 10'],
  ['TREASURE HUNTER GEAR','Treasure Hunter Off-Hand Holster','Treasure Hunter 1'],
  ['TREASURE HUNTER GEAR','Treasure Hunter Bandolier','Treasure Hunter 3'],
  ['TREASURE HUNTER GEAR','Treasure Hunter Gun Belt','Treasure Hunter 7'],
  ['TREASURE HUNTER GEAR','Treasure Hunter Holster','Treasure Hunter 10'],
];

// TRAPPER items: [cat, name, requirements: [[mat, qty], ...]]
// Materials use consistent key names that map to TR_MATS
const TR_MATS_ANIMALS = [
  'Alligator Skin','Armadillo Skin','Badger Pelt','Bear Pelt','Black Bear Pelt',
  'Beaver Pelt','Bison Pelt','Boar Pelt','Buck Pelt','Bull Hide','Cow Hide',
  'Coyote Pelt','Cougar Pelt','Deer Pelt','Elk Pelt','Fox Pelt',
  'Gila Monster Skin','Goat Hide','Iguana Skin','Moose Pelt','Muskrat Pelt',
  'Opossum Pelt','Ox Hide','Panther Pelt','Panther Hide','Peccary Pelt',
  'Pig Hide','Pronghorn Hide','Rabbit Pelt','Ram Hide','Rat Skin',
  'Sheep Hide','Skunk Pelt','Snake Skin','Squirrel Pelt','Wolf Pelt',
];
const TR_MATS_FEATHERS = [
  'Blue Jay Feather','Cardinal Feather','Cedar Waxwing Feather','Chicken Feather',
  'Condor Feather','Crow Feather','Duck Feather','Eagle Feather','Goose Feather',
  'Hawk Feather','Loon Feather','Oriole Feather','Owl Feather','Pheasant Feather',
  'Pigeon Feather','Quail Feather','Raven Feather','Robin Feather','Songbird Feather',
  'Sparrow Feather','Turkey Feather','Vulture Feather',
];
// Legendary pelts are NOT consumed per item — selling 1 pelt to Trapper unlocks ALL
// items from that animal. Track as "have hunted" (toggle), not as a counter.
// Each entry: animal name used as key
const TR_MATS_LEGENDARY = [
  'Legendary Alligator',
  'Legendary Bear',
  'Legendary Beaver',
  'Legendary Boar',
  'Legendary Buck',
  'Legendary Cougar',
  'Legendary Coyote',
  'Legendary Elk',
  'Legendary Fox',
  'Legendary Moose',
  'Legendary Panther',
  'Legendary Pronghorn',
  'Legendary Ram',
  'Legendary Tatanka Bison',
  'Legendary White Bison',
  'Legendary Wolf',
];
// Combined for compatibility
const TR_MATS = [...TR_MATS_ANIMALS, ...TR_MATS_FEATHERS, ...TR_MATS_LEGENDARY];

// TRAPPER GARMENT SETS (16 outfits) — outfit name, then pieces [[pieceName, mats]]
// Each outfit has its component pieces listed underneath for individual tracking
const TR_OUTFITS = [
  { name:'The Bear Hunter', pieces:[
    ['Legendary Bear Head Hat',    [['Legendary Bear',1]]],
    ['Legendary Bear Coat',        [['Legendary Bear',1],['Bison Pelt',1]]],
    ['Legendary Bear Ropers',      [['Legendary Bear',1],['Bull Hide',1]]],
    ['Boar Riding Gloves',         [['Boar Pelt',1],['Rabbit Pelt',2]]],
  ]},
  { name:'The Trophy Buck', pieces:[
    ['Raccoon Mountain Hat',                   [['Muskrat Pelt',1],['Beaver Pelt',1],['Hawk Feather',2]]],
    ['Legendary Buck Vest',                    [['Legendary Buck',1],['Ram Hide',1]]],
    ['Legendary Fox Moccasins',                [['Legendary Fox',1],['Elk Pelt',1]]],
    ['Legendary Buck and Fox Range Gloves',    [['Legendary Buck',1],['Legendary Fox',1]]],
  ]},
  { name:'The Dreamcatcher', pieces:[
    ['Legendary Beaver Flop Hat',            [['Legendary Beaver',1],['Legendary Boar',1],['Cardinal Feather',1]]],
    ['Legendary Bison Vest',                 [['Legendary Tatanka Bison',1]]],
    ['Legendary Bison Batwing Chaps',        [['Legendary Tatanka Bison',1]]],
    ['Legendary Boar and Bison Fowlers',     [['Legendary Boar',1],['Legendary Tatanka Bison',1]]],
    ['Legendary Beaver Cavalry Gloves',      [['Legendary Beaver',1]]],
  ]},
  { name:'The Beast of Prey', pieces:[
    ['Legendary Cougar Flop Hat',           [['Legendary Cougar',1],['Turkey Feather',2]]],
    ['Legendary Cougar and Wolf Vest',      [['Legendary Cougar',1],['Legendary Wolf',1]]],
    ['Legendary Wolf Batwing Chaps',        [['Legendary Wolf',1],['Goat Hide',1]]],
    ['Bull Fowler Boots',                   [['Boar Pelt',1],['Bull Hide',1]]],
    ['Legendary Cougar Riding Gloves',      [['Legendary Cougar',1],['Boar Pelt',1]]],
  ]},
  { name:'The Huntsman', pieces:[
    ['Legendary Coyote Mountain Hat',       [['Legendary Coyote',1],['Eagle Feather',2]]],
    ['Legendary Pronghorn Coat',            [['Legendary Pronghorn',1],['Moose Pelt',1]]],
    ['Legendary Coyote Half Chaps',         [['Legendary Coyote',1],['Fox Pelt',2]]],
    ["Workman's Pride Boots",               [['Cow Hide',1],['Goat Hide',1]]],
    ['Legendary Pronghorn Range Gloves',    [['Legendary Pronghorn',1],['Muskrat Pelt',1]]],
  ]},
  { name:'The Death Roll', pieces:[
    ["Legendary Alligator Gambler's Hat",   [['Legendary Alligator',1],['Snake Skin',2]]],
    ['Legendary Panther Cloak',             [['Legendary Panther',1]]],
    ['Legendary Alligator Vest',            [['Legendary Alligator',1]]],
    ['Legendary Alligator Fowlers',         [['Legendary Alligator',1]]],
    ['Legendary Panther Range Gloves',      [['Legendary Panther',1],['Gila Monster Skin',1]]],
  ]},
  { name:'The Stalker', pieces:[
    ['Legendary Ram Hat',                   [['Legendary Ram',1]]],
    ['Legendary Moose Hunting Jacket',      [['Legendary Moose',1],['Wolf Pelt',1]]],
    ['Legendary Ram Batwing Chaps',         [['Legendary Ram',1]]],
    ['Legendary Moose Moccasins',           [['Legendary Moose',1],['Cow Hide',1]]],
    ['Legendary Ram Rifleman Gloves',       [['Legendary Ram',1],['Boar Pelt',1]]],
  ]},
  { name:'The Ghost Bison', pieces:[
    ['Legendary White Bison Hat',           [['Legendary White Bison',1]]],
    ['Legendary White Bison Coat',          [['Legendary White Bison',1]]],
    ['Legendary Elk Half Chaps',            [['Legendary Elk',1],['Sheep Hide',1]]],
    ['Legendary Elk Moccasins',             [['Legendary Elk',1],['Goat Hide',1]]],
    ['Legendary Elk Range Gloves',          [['Legendary Elk',1]]],
  ]},
  { name:'The Rattler', pieces:[
    ['Ram Sombrero',                        [['Ram Hide',1]]],
    ['Outdoorsmen Vest',                    [['Pronghorn Hide',1]]],
    ['Javelina Half Chaps',                 [['Peccary Pelt',1],['Snake Skin',1]]],
    ['Iguana Range Gloves',                 [['Peccary Pelt',1],['Iguana Skin',1]]],
  ]},
  { name:'The Wrangler', pieces:[
    ['Goat Flop Hat',                       [['Pronghorn Hide',1],['Goat Hide',1]]],
    ["Trapper's Cloak",                     [['Sheep Hide',1]]],
    ["No-Man's Vest",                       [['Panther Hide',1],['Goat Hide',1]]],
    ['Two Toned Moccasins',                 [['Buck Pelt',1]]],
    ['Moose Range Gloves',                  [['Moose Pelt',1]]],
  ]},
  { name:'The Bronco Buster', pieces:[
    ['Elk Flop Hat',                        [['Elk Pelt',1]]],
    ['Coyote Scout Jacket',                 [['Ox Hide',1],['Coyote Pelt',1]]],
    ['Huntsman Vest',                       [['Sheep Hide',1],['Deer Pelt',1]]],
    ['Boar Fringed Shotgun Chaps',          [['Boar Pelt',2]]],
    ['Pigskin Rifleman Gloves',             [['Pig Hide',1]]],
  ]},
  { name:'The Marauder', pieces:[
    ['Muskrat Cavalry Hat',                 [['Rabbit Pelt',4],['Muskrat Pelt',1]]],
    ['Principal Vest',                      [['Cow Hide',1],['Deer Pelt',1]]],
    ['Bull Fringed Shotgun Chaps',          [['Bull Hide',1]]],
    ['Snakeskin Cavalry Gloves',            [['Boar Pelt',1],['Snake Skin',1]]],
  ]},
  { name:'The Bounty Hunter', pieces:[
    ['Plantation Slouch Hat',               [['Bison Pelt',1]]],
    ['Beaver Hunting Jacket',               [['Cow Hide',1],['Beaver Pelt',2]]],
    ['Sheepskin Vest',                      [['Sheep Hide',2]]],
    ['Pronghorn Half Chaps',                [['Pronghorn Hide',1]]],
    ['Buck Riding Gloves',                  [['Buck Pelt',1]]],
  ]},
  { name:'The Desperado', pieces:[
    ['Beaver Drifter Hat',                  [['Beaver Pelt',2]]],
    ['Wolf Coat',                           [['Ram Hide',1],['Wolf Pelt',1]]],
    ['Billy Vest',                          [['Armadillo Skin',1],['Goat Hide',1]]],
    ['Boar and Bull Fowler Boots',          [['Ox Hide',1],['Boar Pelt',1]]],
    ['Winter Cavalry Gloves',               [['Rabbit Pelt',1],['Muskrat Pelt',2]]],
  ]},
  { name:'The Night Wrangler', pieces:[
    ["Coyote Gambler's Hat",                [['Coyote Pelt',2]]],
    ['Cougar Cutaway Coat',                 [['Cougar Pelt',2],['Black Bear Pelt',1]]],
    ['Wilderness Vest',                     [['Wolf Pelt',1],['Panther Pelt',1]]],
    ['Moose Half Chaps',                    [['Moose Pelt',1]]],
    ['Badger Rifleman Gloves',              [['Badger Pelt',1]]],
  ]},
  { name:'The Mountain Man', pieces:[
    ['Grenadier Hat',                       [['Muskrat Pelt',1],['Beaver Pelt',1]]],
    ['Ram Shotgun Coat',                    [['Ram Hide',2]]],
    ['Country Vest',                        [['Buck Pelt',1],['Beaver Pelt',1]]],
    ['Elk Riding Gloves',                   [['Elk Pelt',1]]],
  ]},
];

// TRAPPER INDIVIDUAL ITEMS (not part of named outfits) — [cat, name, mats]
const TR_ITEMS = [
  // HATS
  ['HATS','Badger Mountain Hat',            [['Badger Pelt',1]]],
  ['HATS','Bear Grenadier Hat',             [['Bear Pelt',1]]],
  ['HATS','Beaver Mountain Hat',            [['Beaver Pelt',1]]],
  ['HATS',"Bison Gambler's Hat",            [['Bison Pelt',1]]],
  ['HATS','Deer Cavalry Hat',               [['Deer Pelt',1]]],
  ['HATS','Fox Mountain Hat',               [['Fox Pelt',1]]],
  ['HATS',"Gila Monster Gambler's Hat",     [['Gila Monster Skin',1]]],
  ['HATS','Iguana Big Valley Hat',          [['Iguana Skin',1]]],
  ['HATS','Pronghorn Flop Hat',             [['Pronghorn Hide',1]]],
  ['HATS','Rat Flat Cap',                   [['Rat Skin',2]]],
  ['HATS','Rat Infantry Hardee Hat',        [['Rat Skin',2]]],
  ['HATS','Skunk Mountain Hat',             [['Skunk Pelt',1]]],
  ['HATS','Snake Bulldogger Hat',           [['Snake Skin',1]]],
  ['HATS','Squirrel Flat Cap',              [['Squirrel Pelt',1]]],
  // ACCESSORIES (feather-based)
  ['ACCESSORIES','Glorious Accessory',      [['Turkey Feather',3],['Raven Feather',2]]],
  ['ACCESSORIES','Homestead Accessory',     [['Goose Feather',2],['Robin Feather',2]]],
  ['ACCESSORIES','Huntsman Accessory',      [['Pheasant Feather',2],['Hawk Feather',1]]],
  ['ACCESSORIES','Judicious Accessory',     [['Duck Feather',2],['Eagle Feather',1]]],
  ['ACCESSORIES','Majestic Accessory',      [['Cardinal Feather',2],['Robin Feather',2]]],
  ['ACCESSORIES','Native Accessory',        [['Chicken Feather',2],['Loon Feather',2]]],
  ['ACCESSORIES','Pilgrim Accessory',       [['Condor Feather',1],['Pigeon Feather',1]]],
  ['ACCESSORIES','Pioneer Accessory',       [['Crow Feather',1],['Songbird Feather',1]]],
  ['ACCESSORIES','Pursuer Accessory',       [['Hawk Feather',2],['Cedar Waxwing Feather',2]]],
  ['ACCESSORIES','Rococo Accessory',        [['Quail Feather',1],['Blue Jay Feather',1]]],
  ['ACCESSORIES','Scavenger Accessory',     [['Vulture Feather',1],['Pigeon Feather',1]]],
  ['ACCESSORIES','Stalker Accessory',       [['Sparrow Feather',3],['Oriole Feather',1]]],
  // VESTS
  ['VESTS','Hinterland Vest',               [['Loon Feather',2],['Elk Pelt',1]]],
  ['VESTS','Rugged Wrangler Vest',          [['Oriole Feather',3],['Goose Feather',1]]],
  ['VESTS','Rustic Vest',                   [['Owl Feather',1],['Pheasant Feather',2]]],
  // CHAPS
  ['CHAPS','Batwing Chaps',                 [['Opossum Pelt',1],['Muskrat Pelt',1]]],
  ['CHAPS','Bear Batwing Chaps',            [['Bear Pelt',1],['Bison Pelt',1]]],
  ['CHAPS','Bear Fringed Shotgun Chaps',    [['Bear Pelt',1],['Squirrel Pelt',1]]],
  ['CHAPS','Deer Pelt Half Chaps',          [['Deer Pelt',2]]],
  ['CHAPS','Elk Fringed Shotgun Chaps',     [['Elk Pelt',1],['Rabbit Pelt',1]]],
  ['CHAPS','Moose Batwing Chaps',           [['Moose Pelt',1],['Sheep Hide',1]]],
  ['CHAPS','Muskrat Half Chaps',            [['Muskrat Pelt',3]]],
  ['CHAPS','Ox Fringed Shotgun Chaps',      [['Ox Hide',1],['Rabbit Pelt',1]]],
  ['CHAPS','Sheep Batwing Chaps',           [['Sheep Hide',2]]],
  // BOOTS
  ['BOOTS','Javelina Moccasins',            [['Peccary Pelt',2]]],
  ['BOOTS','Moccasins',                     [['Boar Pelt',1],['Ram Hide',1]]],
  ['BOOTS','Skunk Trapper Boots',           [['Skunk Pelt',2],['Rabbit Pelt',1]]],
  // SADDLES
  ['SADDLES','Alligator Ranch Cutter',      [['Alligator Skin',1]]],
  ['SADDLES','Bear Dakota Saddle',          [['Bear Pelt',1]]],
  ['SADDLES','Beaver Roping Saddle',        [['Beaver Pelt',2]]],
  ['SADDLES','Boar Mother Hubbard Saddle',  [['Boar Pelt',2]]],
  ['SADDLES','Cougar McClelland Saddle',    [['Cougar Pelt',1]]],
  ['SADDLES','Panther Trail Saddle',        [['Panther Pelt',1]]],
  ['SADDLES','Rattlesnake Vaquero Saddle',  [['Snake Skin',2]]],
];

// Keep TR for backward compat (used in overview counts, export, etc.)
// Flatten both outfits pieces and individual items into TR
const TR = [
  ...TR_OUTFITS.flatMap(o => o.pieces.map(([name,mats]) => [`OUTFIT: ${o.name}`, name, mats])),
  ...TR_ITEMS,
];

// CAMP (Pearson): [cat, name, requirements: [[mat, qty], ...]]
const PE = [
  ['SATCHELS','Ingredients Satchel',[['Deer Pelt',1],['Badger Pelt',1],['Squirrel Carcass',1]]],
  ['SATCHELS','Materials Satchel',[['Deer Pelt',1],['Boar Pelt',1],['Iguana Skin',1]]],
  ['SATCHELS','Valuables Satchel',[['Deer Pelt',1],['Beaver Pelt',1],['Rabbit Pelt',1]]],
  ['SATCHELS','Tonics Satchel',[['Deer Pelt',1],['Elk Pelt',1],['Buck Pelt',1]]],
  ['SATCHELS','Kit Satchel',[['Deer Pelt',1],['Elk Pelt',1],['Panther Pelt',1]]],
  ['SATCHELS','Provisions Satchel',[['Deer Pelt',1],['Bison Pelt',1],['Raccoon Pelt',1]]],
  ['SATCHELS','Legend of the East Satchel',[['Deer Pelt',1],['Cougar Pelt',1],['Wolf Pelt',1]]],
  ["ARTHUR'S AREA",'Alligator Skull',[['Alligator Skin',1]]],
  ["ARTHUR'S AREA",'Big Horn Ram Skull',[['Ram Carcass',1]]],
  ["ARTHUR'S AREA",'Cougar Pelt Covered Chest',[['Cougar Pelt',1],['Cougar Pelt',1]]],
  ["ARTHUR'S AREA",'Boar Skin Table Cover',[['Boar Pelt',1]]],
  ["ARTHUR'S AREA",'Ox Hide Rug',[['Ox Hide',1],['Ox Hide',1]]],
  ["JOHN'S AREA","Boar Skin Rug",[['Boar Pelt',1],['Boar Pelt',1],['Boar Pelt',1],['Boar Pelt',1]]],
  ['CAMP TABLE','Pronghorn Leather Table Tops',[['Pronghorn Hide',1],['Pronghorn Hide',1]]],
  ['WAGON','Pronghorn Skull',[['Pronghorn Carcass',1]]],
  ['CAMPFIRE','Moose Antlers',[['Moose Antler',1]]],
  ['CAMPFIRE','Wolf Skull',[['Wolf Carcass',1]]],
  ['CAMPFIRE','Snake Skin Banjo Head',[['Snake Skin',1],['Snake Skin',1]]],
  ['CAMPFIRE','Campfire Seat Cover',[['Beaver Pelt',1],['Muskrat Pelt',1],['Fox Pelt',1]]],
  ['CAMPFIRE','Campfire Log Seat Cover',[['Wolf Pelt',1],['Wolf Pelt',1]]],
  ['CAMPFIRE','Lean-To Cowhide Ground Cover',[['Cow Hide',1]]],
  ['SCOUT FIRE','Scout Fire Ground Cover',[['Goat Hide',1],['Goat Hide',1]]],
  ['SCOUT FIRE','Elk Antlers',[['Elk Antler',1]]],
  ['SCOUT FIRE','Hanging Bones',[['Buck Antler',1]]],
  // LEDGER UPGRADES — Medicine (Strauss's Wagon)
  ['MEDICINE','Sharpen the Senses — Snake Oil & Potent Bitters ($30)',[]],
  ['MEDICINE','Something With Kick — Tonics & Premium Liquors ($50)',[]],
  ['MEDICINE','The Good Stuff — Potent Health Cures & Liquors ($75)',[]],
  // LEDGER UPGRADES — Provisions (Pearson's Wagon)
  ['PROVISIONS','Less Bland — Fresh Fruit & Basic Canned Goods ($30)',[]],
  ['PROVISIONS','Some Real Variety — Better Canned Goods & Seasoned Meat ($45)',[]],
  ['PROVISIONS','Treat Ourselves! — Deluxe Provisions ($55)',[]],
  // LEDGER UPGRADES — Ammunition (Arthur's Wagon)
  ['AMMUNITION','Improve Our Offense — Repeater Ammo & Standard Arrows ($60)',[]],
  ['AMMUNITION','Some Real Firepower — Shotgun, Rifle & Throwing Knives ($90)',[]],
  ["AMMUNITION","Let's Have Some Fun — Fire Bottles & High-Velocity Ammo ($110)",[]], 
  // LEDGER UPGRADES — Crafting
  ['CRAFTING','Leather Working Tools — Unlocks satchel & camp crafting ($225)',[]],
  // LEDGER UPGRADES — Lodging
  ['LODGING','First Things First — Dutch Lodging, boosts gang donations ($220)',[]],
  ['LODGING','Next In Line — Arthur Lodging, unlocks Fast Travel Map ($325)',[]],
  ["LODGING","For Everyone! — All Lodging upgrades ($300)",[]], 
  // LEDGER UPGRADES — Other
  ['OTHER UPGRADES','Horse Station — manage horses from camp ($300)',[]],
  ['OTHER UPGRADES','Chicken Coop — better camp stew & Dead Eye boost ($175)',[]],
  ['OTHER UPGRADES','Camp Boat — boat at camp shoreline ($450)',[]],
];

// CHALLENGES
const CH = {
  'BANDIT':[
    ['Level 1','Hold Up 5 Townsfolk','Bandit Bandolier'],
    ['Level 2','Rob Two Coaches (Missions or Road)','$5 / 25 Dead Eye XP'],
    ['Level 3','Rob Cash Register in 4 Shops in One Day','Bandit Holster'],
    ['Level 4','Rob Three Coaches in One Day','$10 / 50 Dead Eye XP'],
    ['Level 5','Amass $250 Bounty in One State','$10 / 50 Dead Eye XP'],
    ['Level 6','Steal 5 Horses & Sell to Horse Fence','$15 / 100 Dead Eye XP'],
    ['Level 7','Rob $50 Worth of Cash/Valuables from Townsfolk or Travelers','Bandit Off-Hand Holster'],
    ['Level 8','Steal 7 Wagons & Sell to Fence at Emerald Ranch','$15 / 100 Dead Eye XP'],
    ['Level 9','Hogtie Someone & Leave on Railroad 3 Times','$20 / 150 Dead Eye XP'],
    ['Level 10','Rob 5 Trains Without Dying or Being Caught','Bandit Gun Belt'],
  ],
  'EXPLORER':[
    ['Level 1','Find a Treasure Map','Explorer Holster'],
    ['Level 2','Find a Treasure','$5 / 25 Stamina XP'],
    ['Level 3','Find a Treasure','Explorer Bandolier'],
    ['Level 4','Find a Treasure','$10 / 50 Stamina XP'],
    ['Level 5','Find a Treasure','$10 / 50 Stamina XP'],
    ['Level 6','Find a Treasure','$15 / 100 Stamina XP'],
    ['Level 7','Find a Treasure','Explorer Gun Belt'],
    ['Level 8','Find a Treasure','$15 / 100 Stamina XP'],
    ['Level 9','Find a Treasure','$20 / 150 Stamina XP'],
    ['Level 10','Find a Treasure','Explorer Off-Hand Holster'],
  ],
  'GAMBLER':[
    ['Level 1','Win Five Hands of Poker','Gambler Holster'],
    ['Level 2','In Blackjack, Double Down and Win the Hand 5 Times','$5 / 25 Dead Eye XP'],
    ['Level 3','Win Three Games of Five Finger Fillet','Gambler Bandolier'],
    ['Level 4','Bust One Poker Opponent Out in Flatneck, Saint Denis & Valentine','$10 / 50 Dead Eye XP'],
    ['Level 5','Win 3 Rounds of Dominoes Without Drawing Tiles vs ≤2 Opponents','$10 / 50 Dead Eye XP'],
    ['Level 6','Beat Blackjack Dealer in Rhodes and Van Horn','$15 / 100 Dead Eye XP'],
    ['Level 7','Beat Five Finger Fillet in Strawberry, Valentine, and Van Horn','Gambler Gun Belt'],
    ['Level 8','Win 3 Hands of Blackjack With 3+ Hits','$15 / 100 Dead Eye XP'],
    ['Level 9','Win Three Games of Dominoes in a Row','$20 / 150 Dead Eye XP'],
    ['Level 10','Win Three Hands of Poker in a Row','Gambler Off-Hand Holster'],
  ],
  'HERBALIST':[
    ['Level 1','Pick Six Yarrow','Herbalist Off-Hand Holster'],
    ['Level 2','Pick and Eat Four Species of Berry','$5 / 25 Health XP'],
    ['Level 3','Craft Seven Items Using Sage as an Ingredient','Herbalist Gun Belt'],
    ['Level 4','Pick Five Mushrooms and Feed Them to Your Horse','$10 / 50 Health XP'],
    ['Level 5','Craft Nine Items Using Indian Tobacco as an Ingredient','$10 / 50 Health XP'],
    ['Level 6','Pick 15 Different Species of Herbs','$15 / 100 Health XP'],
    ['Level 7','Craft and Use Five Special Miracle Tonics','Herbalist Holster'],
    ['Level 8','Use Oleander to Craft Six Poison Weapons','$15 / 100 Health XP'],
    ['Level 9','Pick One of Each Species of Herb','$20 / 150 Health XP'],
    ['Level 10','Season and Cook All Eleven Types of Meat','Herbalist Bandolier'],
  ],
  'HORSEMAN':[
    ['Level 1','Kill Five Rabbits from Horseback','Horseman Gun Belt'],
    ['Level 2','Jump Over Three Obstacles in 15 Seconds','$5 / 25 Stamina XP'],
    ['Level 3','Ride Valentine to Rhodes in Less Than 5 Minutes','Horseman Holster'],
    ['Level 4','While Mounted, Drag a Victim 3,300 Feet Using Your Lasso','$10 / 50 Stamina XP'],
    ['Level 5','Trample Five Animals While on Horseback','$10 / 50 Stamina XP'],
    ['Level 6','Ride Strawberry to Saint Denis in Under 9 Minutes Without Touching Water','$15 / 100 Stamina XP'],
    ['Level 7','Kill Seven Enemies From Horseback Without Dismounting','Horseman Bandolier'],
    ['Level 8','Kill Nine Predators From Horseback','$15 / 100 Stamina XP'],
    ['Level 9','Ride Van Horn to Blackwater in Under 17 Minutes Without Touching Water','$20 / 150 Stamina XP'],
    ['Level 10','Break Every Wild Horse Breed','Horseman Off-Hand Holster'],
  ],
  'MASTER HUNTER':[
    ['Level 1','Skin Three Deer','Master Hunter Off-Hand Holster'],
    ['Level 2','Get Three Perfect-Quality Rabbit Pelts','$5 / 25 Health XP'],
    ['Level 3','Track 10 Different Animal Species Using Your Binoculars','Master Hunter Bandolier'],
    ['Level 4','Get a Clean Kill After Calling to an Animal 5 Times','$10 / 50 Health XP'],
    ['Level 5','Skin Three Bears (Black or Grizzly)','$10 / 50 Health XP'],
    ['Level 6','Kill and Skin Five Cougars With Your Bow','$15 / 100 Health XP'],
    ['Level 7','Use Bait to Lure and Kill a Herbivore and a Predator','Master Hunter Gun Belt'],
    ['Level 8','Catch Three Fish Without Using a Fishing Rod','$15 / 100 Health XP'],
    ['Level 9','Catch an Opossum Playing Possum','$20 / 150 Health XP'],
    ['Level 10','Find and Kill All 16 Legendary Animals','Master Hunter Holster'],
  ],
  'SHARPSHOOTER':[
    ['Level 1','Get 10 Headshot Kills','Sharpshooter Off-Hand Holster'],
    ['Level 2','Kill 5 Flying Birds With a Varmint Rifle','$5 / 25 Dead Eye XP'],
    ['Level 3','Kill Someone 80+ Feet Away With a Throwing Knife','Sharpshooter Bandolier'],
    ['Level 4','Disarm 3 Enemies Without Killing Them','$10 / 50 Dead Eye XP'],
    ['Level 5','Kill 6 Animals Without Changing or Reloading Your Weapon','$10 / 50 Dead Eye XP'],
    ['Level 6','Shoot 3 Enemies Off Their Horses in the Same Day','$15 / 100 Dead Eye XP'],
    ['Level 7','Kill 3 Enemies in 10 Seconds Using Only a Bow','Sharpshooter Gun Belt'],
    ['Level 8','Kill 2 Different Animal Species in Same Dead Eye Activation','$15 / 100 Dead Eye XP'],
    ["Level 9","While in Dead Eye, Shoot the Hat Off a Stranger's Head",'$20 / 150 Dead Eye XP'],
    ['Level 10','Kill 3 Flying Birds With 3 Consecutive Shots Using a Repeater','Sharpshooter Holster'],
  ],
  'SURVIVALIST':[
    ['Level 1','Catch Three Bluegill Fish','Survivalist Gun Belt'],
    ['Level 2','Hand Five Animals in to Pearson at Camp or to the Trapper','$5 / 25 Stamina XP'],
    ['Level 3','Kill Five Animals With the Varmint Rifle','Survivalist Off-Hand Holster'],
    ['Level 4','Craft All of the Arrow Types','$10 / 50 Stamina XP'],
    ['Level 5','Catch a Fish in the Bayou From a Riverboat and While Standing on Railroad Tracks','$10 / 50 Stamina XP'],
    ['Level 6','Kill a Scavenging Animal While it is Feeding on a Corpse Five Times','$15 / 100 Stamina XP'],
    ['Level 7','Kill Eight Small Game Animals With Consecutive Shots Using Small Game Arrows','Survivalist Bandolier'],
    ['Level 8','Craft a Homing Tomahawk, Improved Tomahawk, Volatile Dynamite, and Volatile Fire Bottle','$15 / 100 Stamina XP'],
    ['Level 9','Catch a Fish That Weighs at Least 19 lbs','$20 / 150 Stamina XP'],
    ['Level 10','Catch One of Each Type of Fish in the World','Survivalist Holster'],
  ],
  'WEAPONS EXPERT':[
    ["Level 1","Kill Three Enemies with a Knife",'Weapons Expert Holster'],
    ['Level 2','Kill Three Enemies in 10 Seconds Using Only Throwing Knives','$5; 25 Health XP'],
    ['Level 3','Kill Three Birds of Prey Using Only a Tomahawk','Weapons Expert Gun Belt'],
    ['Level 4','Kill 10 Enemies With a Shotgun Using Crafted Ammo','$10; 50 Health XP'],
    ['Level 5','Kill Five Mounted Enemies, Using One Throwing Knife per Kill','$10; 50 Health XP'],
    ['Level 6','Kill Four Enemies at the Same Time With a Single Stick of Dynamite','$15; 100 Health XP'],
    ['Level 7','Kill Four Consecutive Enemies by Throwing and Retrieving the Same Tomahawk','Weapons Expert Off-Hand Holster'],
    ['Level 8','Kill 15 Enemies Using a Long-barreled Sidearm','$15; 100 Health XP'],
    ['Level 9','Kill Nine Unaware Enemies From Behind Using the Bow','$20; 150 Health XP'],
    ['Level 10','Kill a Grizzly Bear Without Taking Damage, Using Only Throwing Knives','Weapons Expert Bandolier'],
  ],
};

// STORY
const ST = {
  'Chapter 1':['Outlaws from the West',
  'Enter, Pursued by a Memory',
  'The Aftermath of Genesis',
  'Old Friends',
  'Who the Hell is Leviticus Cornwall?',
  'Eastward Bound',],  
  
  'Chapter 2':['Polite Society, Valentine Style',
'Americans at Rest',
'Who is Not without Sin',
'Exit Pursued by a Bruised Ego',
'The First Shall be Last',
'Paying a Social Call',
'A Quiet Time',
'Blessed are the Meek?',
'Good, Honest, Snake Oil',
'We Loved Once and True (I, II, III)',
'Money Lending and Other Sins I & II',
'Money Lending and Other Sins III',
'The Spines of America',
'Pouring Forth Oil (I & II)',
'Pouring Forth Oil – III & IV',
'A Fisher of Men',
'An American Pastoral Scene',
'The Sheep and the Goats',
'A Strange Kindness'],
  
  'Chapter 3':['The New South',
'Further Questions of Female Suffrage',
'Money Lending and Other Sins IV',
'American Distillation',
'The Course of True Love – I & II',
'The Course of True Love III',
'Advertising, the New American Art (I & II)',
'Horse Flesh for Dinner',
'The Fine Joys of Tobacco',
'Magicians for Sport',
'Friends in Very Low Places',
'An Honest Mistake',
'Preaching Forgiveness As He Went',
'Sodom? Back to Gomorrah',
'Blessed are the Peacemakers',
'A Short Walk in a Pretty Town',
'Blood Feuds, Ancient and Modern',
'The Battle of Shady Belle'],
 
  'Chapter 4':['The Joys of Civilization',
'Angelo Bronte, a Man of Honor',
'Money Lending and Other Sins – V',
'Help a Brother Out',
'Brothers and Sisters, One and All',
'Fatherhood and Other Dreams (I & II)',
'No, No and Thrice, No',
'The Gilded Cage',
'A Fine Night of Debauchery',
'American Fathers (I & II)',
'High and Low Finance',
'Horsemen, Apocalypses',
'Urban Pleasures',
'Country Pursuits',
'Revenge is a Dish Best Eaten',
'Banking, the Old American Art'],
 
  'Chapter 5':['Welcome to the New World',
'Savagery Unleashed',
'A Kind and Benevolent Despot',
'Hell Hath No Fury',
'Paradise Mercifully Departed',
'Dear Uncle Tacitus',
'Fleeting Joy',
'A Fork in the Road',
"That's Murfree Country"],

  'Chapter 6':['Icarus and Friends',
'Visiting Hours',
'Just a Social Call',
'Do Not Seek Absolution – I',
'Do Not Seek Absolution – II',
'Of Men And Angels',
'The Course of True Love – IV & V',
'Money Lending and Other Sins – VI & VII',
'The Delights of Van Horn',
'The Bridge to Nowhere',
'A Rage Unleashed',
'Archaeology for Beginners',
'Honor, Amongst Thieves',
'The Fine Art of Conversation',
'Goodbye, Dear Friend',
'Mrs. Sadie Adler, Widow (I & II)',
'Favored Sons',
"The King's Son",
'My Last Boy',
'Our Best Selves',
'Red Dead Redemption'],

  'Epilogue I':['The Wheel',
'Simple Pleasures',
'Farming, for Beginners',
'Fatherhood, for Beginners',
'Old Habits',
'Jim Milton Rides, Again?',
'Fatherhood, for Idiots',
'Motherhood',
'Gainful Employment',
'The Landowning Classes / Home of the Gentry?'],

  'Epilogue II':['Bare Knuckles Friendships',
'Home Improvement for Beginners',
"An Honest Day's Labors",
'The Tool Box',
'A New Jerusalem',
'A Quick Favor for an Old Friend',
"Uncle's Bad Day",
'Trying Again',
'A Really Big Bastard',
'A New Future Imagined',
'American Venom',],
};

// ACHIEVEMENTS — PS5 trophy list (51 trophies excl. Platinum)
// [name, category, type, description]
const AC = [
  // ── STORY ──
  ['Back in the Mud','Story','bronze','Complete Chapter 1'],
  ['Just a Scratch','Story','bronze','Complete "Enter, Pursued by a Memory"'],
  ['To Greener Pastures','Story','bronze','Complete Chapter 2'],
  ['Settling Feuds','Story','bronze','Complete Chapter 3'],
  ['Washed Ashore','Story','bronze','Complete Chapter 4'],
  ['No Traitors','Story','bronze','Complete Chapter 5'],
  ['Third Time Lucky','Story','bronze','Complete "Goodbye, Dear Friend"'],
  ['Redemption','Story','silver','Complete "Red Dead Redemption"'],
  ['Cowboy Builder','Story','bronze','Complete "A New Jerusalem"'],
  ['Endless Summer','Story','gold','Complete the Epilogue'],
  // ── MISSABLE STORY ──
  ['Lending a Hand','Story (Missable)','silver','Complete all optional Honor story missions'],
  ['Friends With Benefits','Story (Missable)','bronze','Complete a Companion Activity in each camp'],
  ['Errand Boy','Story (Missable)','bronze','Deliver 5 camp companion item requests'],
  // ── COMPLETION ──
  ['Best in the West','Completion','gold','Attain 100% completion'],
  ['Gold Rush','Completion','silver','Earn 70 Gold Medals in Story missions'],
  // ── EXPLORATION ──
  ['Paying Respects','Exploration','bronze','Find the graves of each of your fallen companions'],
  ["Collector's Item",'Exploration','silver','Complete one of the Collectable strands'],
  ["It's Art",'Exploration','bronze','Find a permanent home for the squirrel statue'],
  ['Artificial Intelligence','Exploration','bronze','Discover the fate of Marko Dragic'],
  ['Western Stranger','Exploration','bronze','Complete 10 Stranger mission strands'],
  // ── COMBAT / CHALLENGES ──
  ['Grin and Bear It','Combat','bronze','Survive 18 bear attacks and kill the bear each time'],
  ['Bountiful','Wanted','bronze','Survive 3 days holding a $250 bounty in all states'],
  // ── ECONOMY ──
  ['Take From the Rich','Economy','bronze','Rob or loot $250'],
  ['Give to the Poor','Economy','bronze','Donate $250 to the gang tithing box'],
  ['Pony Up','Economy','bronze','Spend $5,000 across all shops'],
  // ── LIFESTYLE ──
  ['Extreme Personality','Honor','bronze','Reach maximum or minimum Honor level'],
  ['Hobby Horse','Minigames','bronze','Play all mini games'],
  ['Breaking and Entering','Crime','bronze','Recover the stash from 4 homesteads'],
  ['Trusty Steed','Horses','bronze','Reach max bonding level with a horse'],
  // ── HUNTING & CRAFTING ──
  ['Zoologist','Hunting','bronze','Study every animal across all states in Story Mode'],
  ['Skin Deep','Hunting','bronze','Skin every species of animal in Story Mode'],
  ["It Was THIS Big!",'Fishing','bronze','Catch a fish weighing at least 16 lbs'],
  ['Self Sufficient','Crafting','bronze','Craft 30 unique items in Story Mode'],
  ['Locked and Loaded','Weapons','bronze','Upgrade each available component for a single sidearm or longarm'],
  // ── RED DEAD ONLINE ──
  ['Breakout','Online','bronze','Complete the Online Intro'],
  ['Series Major','Online','bronze','Take part in a Series'],
  ['Gun For Hire','Online','bronze','Accept 10 Free Roam missions from characters'],
  ['Eventful','Online','bronze','Play 5 Free Roam Events'],
  ['Buckle Up','Online','bronze','Achieve 5 gold belt buckles from awards'],
  ['The Real Deal','Online','bronze','Achieve MVP 3 times in a round with at least 4 players'],
  ['Horses for Courses','Online','bronze','Concurrently own 5 horses'],
  ['Getting Started','Online','bronze','Reach Rank 10'],
  ['Notorious','Online','gold','Reach Rank 50'],
  ["All's Fair",'Online','bronze',"Counter a rival Posse's Free Roam mission"],
  ['Home Comforts','Online','bronze','Purchase 5 camp improvements'],
  ['Non-Regulation','Online','bronze','Craft 25 pieces of ammunition'],
  ['Posse Up','Online','bronze','Form a Persistent Posse'],
  ['Master Craftsman','Online','bronze','Craft 20 items (excluding ammo)'],
  ['Butchered','Online','bronze','Sell 20 items to the Butcher'],
  ['Picked to Perfection','Online','bronze','Pick 25 Herbs'],
  ['Strength in Numbers','Online','bronze','Complete a Free Roam mission as part of a Posse with 2+ members'],
];

// CIGARETTE CARDS
const CIG = {
  'Famous Gunslingers':{reward:'Special Snake Oil, $50',cards:[
    ['No. 1 Frank Heck','New Hanover','Valentine','Cemetery, base of a tombstone'],
    ['No. 2 Otis Miller Boys','New Hanover','Six Point Cabin','Wagon, to the east'],
    ['No. 3 Jack Hall Gang','Ambarino','Chez Porter','Windowsill'],
    ['No. 4 Butcher Brothers','New Hanover','Butcher Creek','Barrel (red top)'],
    ['No. 5 Flaco Hernandez','Lemoyne','Rhodes','Bank, roof'],
    ['No. 6 Slim Grant','Ambarino','Fairview Shanty','Barrel'],
    ['No. 7 Landon Ricketts','New Austin','Armadillo','House across from undertaker, out back'],
    ['No. 8 Black Belle','West Elizabeth','Blackwater','Pier, barrel'],
    ['No. 9 Billy Midnight','New Austin','Tumbleweed','Windmill'],
    ['No. 10 Emmet Granger','Lemoyne','Canebreak Manor','Barrel'],
    ["No. 11 Jim 'Boy' Calloway",'Lemoyne','Saint Denis','Graveyard, inside NW mausoleum'],
    ['No. 12 Bart Love','West Elizabeth','Hanging Dog Ranch','House, by the couch'],
  ]},
  'Artists':{reward:'Ginseng Elixir, $100',cards:[
    ['No. 1 Edith Corinne','Lemoyne','Braithwaite Manor','Central grounds, large clothesline, table'],
    ['No. 2 Elsie Rose','West Elizabeth','Strawberry','Hotel, upstairs on a table'],
    ['No. 3 W.G. Hoyt','New Hanover',"Hani's Bethel",'Table'],
    ['No. 4 Aldous Bramley','West Elizabeth','Blackwater','House south of town, porch'],
    ['No. 5 Preston T. Stephenson','New Hanover','Annesburg','Mining office, table'],
    ['No. 6 Evelyn Miller','West Elizabeth','Blackwater','Clothesline, nearby table'],
    ['No. 7 Slick Hutton','New Hanover','Van Horn Mansion','Balcony'],
    ['No. 8 Laurence Carson','Lemoyne','Saint Denis',"Trapper's market, pig alley, desk"],
    ['No. 9 Miss Maud Delancy','Lemoyne','Houseboat','Table'],
    ['No. 10 Charles Chatenay','New Hanover','Chadwick Farm','Porch'],
    ['No. 11 George Dixie','New Hanover','Guthrie Farm','In house on bed, next to guitar'],
    ['No. 12 Richard McCullough','Lemoyne','Saint Denis',"Near Algernon's greenhouse, patio w/ gazebo, table"],
  ]},
  'Vistas of America':{reward:'Gold Nugget, $100',cards:[
    ['No. 1 New York','Lemoyne','Caliga Hall','Row of houses, porch'],
    ['No. 2 Saint Denis','Lemoyne','Saint Denis','Train station, cart'],
    ['No. 3 Blackwater','West Elizabeth','Blackwater','Theater, roof, on a table'],
    ['No. 4 Armadillo','New Austin','Armadillo','Pig pens, barrel'],
    ['No. 5 Rio Bravo','New Hanover','Flatneck Station','Windmill'],
    ['No. 6 The Grizzlies','New Austin','Lake Don Julio','Shack'],
    ['No. 7 San Francisco','New Hanover','Fort Brennand','Tower, windowsill'],
    ['No. 8 Tall Trees','New Hanover','Flatneck Station','Outside, barrel'],
    ['No. 9 Valentine','New Hanover','Valentine','Train station'],
    ['No. 10 Chicago','New Hanover','Emerald Ranch','Windmill'],
    ['No. 11 Rhodes','Lemoyne','Rhodes','Cemetery, headstone near open grave'],
    ['No. 12 Annesburg','New Hanover','Annesburg','Elevated mining cart tracks, barrel'],
  ]},
  'Gems of Beauty':{reward:'Platinum Chain Necklace, $100',cards:[
    ['No. 1 Leila Stetson','New Hanover','Carmody Dell','Inside house, window left of fireplace'],
    ['No. 2 Isabelle Barlow','New Hanover','Abandoned Trading Post','Shelf, inside'],
    ['No. 3 Hattie Langtry','New Hanover','Meteor House','Inside, table'],
    ['No. 4 Isabelle Standish','New Hanover','Annesburg','Inside mine (S), table'],
    ['No. 5 Maud Engel','New Hanover','Heartland Oil Fields','S of tracks, back porch, table'],
    ['No. 6 Sadie Russell','West Elizabeth','Blackwater','Chicken coop near barber, barrel'],
    ['No. 7 Geraldine Emerson','West Elizabeth','Hanging Dog Ranch','Barn, top floor, crate'],
    ['No. 8 Agnes Guyon','Ambarino','Millesani Claim','Shack, inside, box'],
    ['No. 9 Jennie Willetts','New Hanover','Van Horn','Fenced yard, barrel'],
    ['No. 10 Ilga Ulmer','Lemoyne','Saint Denis','Alley behind doctor, table'],
    ['No. 11 Fay Delaro','New Hanover','Valentine','SW barn, upper level, window'],
    ['No. 12 Pauline Henderson','New Hanover','Bacchus Station','Crate'],
  ]},
  'Flora of America':{reward:'Special Miracle Tonic, $50',cards:[
    ['No. 1 Golden Currant','Lemoyne','Lakay','Shack, shelf'],
    ['No. 2 Hummingbird Sage','New Hanover','Butcher Creek','SE of town, shack, table'],
    ['No. 3 Oleander Sage','Lemoyne','Saint Denis','Behind Rose & Oliver restaurant, brown staircase ledge'],
    ['No. 4 Yarrow','Lemoyne','Lakay','Cabin railing'],
    ['No. 5 Indian Tobacco','Lemoyne','Lakay','Crate to left of house'],
    ['No. 6 Black Mangrove','New Hanover','Emerald Ranch','Train station, barrel'],
    ['No. 7 Longleaf Pine','New Hanover','Annesburg','Inside mine, SW entrance, final platform'],
    ['No. 8 Desert Fan Palm','New Austin','Tumbleweed','Big house to the west, porch'],
    ['No. 9 Coastal Redwood','West Elizabeth','Strawberry','House S of town, back porch'],
    ['No. 10 Horse Crippler Cactus','Lemoyne','Caliga Hall','Workbench, shack by docks'],
    ['No. 11 Blazing Star','West Elizabeth',"Vetter's Echo",'Railing'],
    ['No. 12 Carolina Lupine','New Austin','Tumbleweed',"Sheriff's Office (not jail), roof"],
  ]},
  'Stars of the Stage':{reward:'Small Jewelry Bag, $50',cards:[
    ['No. 1 Laurence Dunn','Lemoyne','Robard Farm','Mantle'],
    ['No. 2 Louis Dunrand','New Hanover','Van Horn','House W of town, porch'],
    ['No. 3 Jesse Raymond','New Austin','Tumbleweed','Burned house to N, windowsill'],
    ['No. 4 Augusta Tremlow','West Elizabeth','Hanging Dog Ranch','Windmill'],
    ['No. 5 Mabel Potter','Lemoyne','Saint Denis','Theater, table in hallway'],
    ['No. 6 Robin Koninsky','Lemoyne','Saint Denis','Theater, wings of stage (see 5 shows first)'],
    ['No. 7 Isadore Reid','New Hanover','Valentine','Near theater tent, wagon'],
    ['No. 8 Irene Grubb','New Austin',"Macfarlane's Ranch",'Train station, bench'],
    ['No. 9 Nettie Palmer','New Hanover','Valentine','Theater tent, under projector'],
    ['No. 10 Jim Cobb','Lemoyne',"Compson's Stead",'Porch, bench'],
    ['No. 11 Mittie Comstock','New Hanover','Larned Sod','Barrel'],
    ['No. 12 Robert Elliot Patchen','Lemoyne','Rhodes','Near Fence, yellow house, crate'],
  ]},
  'Fauna of America':{reward:'Perfect Rabbit Pelt, $50',cards:[
    ['No. 1 Black Widow Spider','West Elizabeth',"Vetter's Echo",'Inside (caution: bear)'],
    ['No. 2 Bloodhound','Lemoyne','Bolger Blade','Ruined house, fireplace'],
    ['No. 3 Bluejay','New Hanover','Clingman','Viewing platform, tree'],
    ['No. 4 Catfish','Lemoyne','Saint Denis','West dock, barrel'],
    ['No. 5 Coral Snake','Lemoyne','Lakay','Fire mural on biggest house, bench'],
    ['No. 6 Grouper','Lemoyne','Lagras','Fishing boat, barrel'],
    ['No. 7 Large Mouth Bass','New Hanover',"Gill's Landing",'Under couch'],
    ['No. 8 Panther','New Hanover','Fort Brennand','Cabin, inside, crate'],
    ['No. 9 Parrot','Lemoyne',"Macomb's End",'Pier, crate'],
    ['No. 10 Pheasant','New Hanover','Clingman','Viewing platform, tree'],
    ['No. 11 Snapping Turtle','New Hanover','Firewood Rise','Under dresser'],
    ['No. 12 Turkey','New Hanover','Van Horn','Burned building, upstairs, fireplace'],
  ]},
  'Marvels of Travel':{reward:'Aged Pirate Rum, $50',cards:[
    ['No. 1 Packet Ship','New Hanover','Annesburg','Dock, under roofed area, crate'],
    ['No. 2 Schooner','New Hanover','Van Horn','Houseboat, under bed'],
    ['No. 3 Camel Caravan','Lemoyne','Rhodes','Near saloon, clothesline table'],
    ['No. 4 Elephant Carriage','West Elizabeth','Strawberry',"Tracker's Hotel, rear staircase, railing"],
    ['No. 5 Goat Carriage','New Hanover','Emerald Ranch','Stables, workbench'],
    ['No. 6 Hot Air Balloon','Lemoyne','Saint Denis','Saloon (E), shelf'],
    ['No. 7 U.S. Frigate','Lemoyne','Braithwaite Manor','Near docks, workshop with boat, table'],
    ['No. 8 The Showboat','Lemoyne','Saint Denis','Pier (S), fish-gutting table'],
    ['No. 9 Balener Whaling Vessel','Lemoyne','Saint Denis','Docks, blue octagonal building, sill'],
    ['No. 10 Stagecoach','West Elizabeth','Riggs Station','Bench'],
    ['No. 11 Steam Locomotive II','Lemoyne','Clemens Point','Wall, ruined house to north'],
    ['No. 12 Velocipede','Lemoyne','Saint Denis','Big fancy green house E of Mayor, W side porch, table'],
  ]},
  'World Champions':{reward:'Valerian Root, $50',cards:[
    ['No. 1 Percy Wood','New Hanover','Butcher Creek','Shack S of town, nearby well'],
    ['No. 2 Edwin A. Rowe','New Hanover',"Clawson's Rest",'Windowsill'],
    ['No. 3 Theobald Getzin','New Hanover','Emerald Ranch','House to N, shelf'],
    ['No. 4 H.T. Solcum','Lemoyne','Canebreak Manor','Under shack, box'],
    ['No. 5 Felix Hawley','New Hanover',"Maclean's House",'Side of house, table'],
    ['No. 6 Patsey Hill','Lemoyne','Trail Rise','Basement, shelf'],
    ['No. 7 R.S. Harradon','Lemoyne','Saint Denis','House E of graveyard, back porch, planks railing'],
    ['No. 8 William Sleicher','New Hanover','Heartland Oil Fields','S of tracks, back porch, table'],
    ['No. 9 E.D. Ewing "Walker"','New Hanover','Annesburg','Mining tower'],
    ['No. 10 Edwin Singerly','Ambarino','Barrow Lagoon','Cabin, inside, table'],
    ['No. 11 Capt. Jack Page','New Hanover',"Clawson's Rest",'Windowsill'],
    ['No. 12 Axel McCormack','Lemoyne','Saint Denis','Saloon (W), rear courtyard, crate'],
  ]},
  'Amazing Inventions':{reward:'Volatile Dynamite, $100',cards:[
    ['No. 1 Steam Locomotive','Lemoyne','Bolger Blade','Ruined church, upper level, bird nest on ledge'],
    ['No. 2 Camera','Lemoyne','Saint Denis','Near photo studio, balcony'],
    ['No. 3 Electrical Execution','West Elizabeth','Hanging Dog Ranch','House, under bunk beds'],
    ['No. 4 Typewriter','West Elizabeth','Blackwater','Warehouse W of post office, corner next to ramp, barrel'],
    ['No. 5 Revolver','New Hanover','Annesburg','Gunsmith, out back, table'],
    ['No. 6 Telegraph','New Hanover','Van Horn','Train station, bench'],
    ['No. 7 Manned Glider','Lemoyne','Caliga Hall','Barn, inside on bench'],
    ['No. 8 Dynamite','Lemoyne','Shady Belle','Porch'],
    ['No. 9 Cylinder Phonograph','New Hanover','Valentine','Saloon, windowsill'],
    ['No. 10 Player Piano','Lemoyne','Saint Denis','Saloon (W), piano'],
    ['No. 11 Electric Lightbulb','New Hanover','Doverhill','Rear door, box'],
    ['No. 12 Telephone','New Hanover','Annesburg','Mine interior, final chamber, table'],
  ]},
  'Historical Figures':{reward:'Special Bitters, $100',cards:[
    ['No. 1 Abraham Lincoln','Lemoyne','Saint Denis','Hotel (W), lobby, shelf by clock'],
    ['No. 2 Albert Einstein','New Hanover','Emerald Ranch','Train station, on a bench'],
    ['No. 3 Calamity Jane','West Elizabeth','Blackwater','Hotel, upstairs, table'],
    ['No. 4 Charles Darwin','Lemoyne','Saint Denis','Museum of Art, lower level, table'],
    ['No. 5 Frederick Douglass','Lemoyne','Saint Denis','Warehouse off the docks, box'],
    ['No. 6 Geronimo','New Hanover','Van Horn','Ruined building, crate'],
    ['No. 7 Harriet Tubman','New Hanover','Annesburg','Church, inside, pew'],
    ['No. 8 Jesse James','New Hanover','Flatneck Station','Train station platform, barrel'],
    ['No. 9 Mark Twain','New Hanover','Emerald Ranch','House to the north, shelf'],
    ['No. 10 Nikola Tesla','West Elizabeth','Blackwater','Power station, table'],
    ['No. 11 P.T. Barnum','New Hanover','Valentine','Stable roof, barrel'],
    ['No. 12 Sitting Bull','Ambarino','Wapiti Indian Reservation','Large building, on a table'],
  ]},
  'Anatomy of the Horse':{reward:'Horse Stimulant, $50',cards:[
    ['No. 1 The Frame','New Hanover','Heartland Oil Fields','N of tracks, house to the right, shelf'],
    ['No. 2 The Muscular System','New Hanover','Annesburg','Mining company office, shelf'],
    ['No. 3 The Dental System','New Hanover','Van Horn','Burned building remains, box'],
    ['No. 4 The Digestive System','Lemoyne','Caliga Hall','Row of houses, inside one, shelf'],
    ['No. 5 The Respiratory System','West Elizabeth','Blackwater','Stable, hay bale'],
    ['No. 6 The Circulatory System','New Hanover','Chadwick Farm','Inside house, table'],
    ["No. 7 The Nervous System",'West Elizabeth','Strawberry',"Doctor's office, shelf"],
    ['No. 8 The Integumentary System','New Hanover','Valentine','Post office, box in corner'],
    ['No. 9 The Reproductive System','West Elizabeth','Hanging Dog Ranch','Inside barn, crate near horse stall'],
    ['No. 10 The Immune System','New Hanover','Annesburg','Near mineshaft entrance, barrel'],
    ['No. 11 Locomotion I','Lemoyne','Lagras','Shack to the southeast, shelf'],
    ['No. 12 Locomotion II','New Hanover','Butcher Creek','Ruined building, fireplace mantle'],
  ]},
};

const DINO_BONES = [
  ['Bone 1','Heartlands','Southeast of Horseshoe Overlook, near the dried riverbed'],
  ['Bone 2','Heartlands','North of Flatneck Station, rocky outcrop'],
  ['Bone 3','Cholla Springs','West of Armadillo, base of the canyon wall'],
  ['Bone 4','Cholla Springs','South of Tumbleweed, near the old ruins'],
  ['Bone 5','Roanoke Ridge','North of Annesburg, cliffside near the mine'],
  ['Bone 6','Roanoke Ridge','East of Butcher Creek, rocky hillside'],
  ['Bone 7','Grizzlies East','Near Whinyard Strait, frozen lakeside'],
  ['Bone 8','Grizzlies East','Southwest of Barrow Lagoon, snowy ridge'],
  ['Bone 9','Grizzlies West','North of Window Rock, stone ledge'],
  ['Bone 10','Grizzlies West','Near the summit of Mount Hagen'],
  ['Bone 11','Big Valley','Southeast of Owanjila Dam, hillside'],
  ['Bone 12','Big Valley','Near Black Bone Forest, rocky terrain'],
  ['Bone 13','Tall Trees','Along the Upper Montana River, riverbank'],
  ['Bone 14','Tall Trees','South of Nekoti Rock, forest floor'],
  ['Bone 15','Great Plains','Northeast of Blackwater, open plains'],
  ['Bone 16','Great Plains','Near Flat Iron Lake, southern shore'],
  ['Bone 17','Bayou Nwa','East of Lagras, swamp edge'],
  ['Bone 18','Bayou Nwa','Near Lakay, north of the settlement'],
  ['Bone 19','Bluewater Marsh','West of Caliga Hall, marshland'],
  ['Bone 20','Bluewater Marsh','North of Rhodes, elevated ridge'],
  ['Bone 21','Scarlett Meadows','Near the Ringneck Creek, canyon floor'],
  ['Bone 22','Scarlett Meadows','Southwest of Braithwaite Manor'],
  ['Bone 23','Stillwater Creek','Along the creek bed, east side'],
  ['Bone 24','Hennigans Stead','Near the old farm ruins'],
  ['Bone 25','Rio Bravo','South of Thieves Landing, dry gulch'],
  ['Bone 26','Rio Bravo','Near the Manteca Falls, rocky base'],
  ['Bone 27','Río Bravo','West of Del Lobo Rock'],
  ['Bone 28','Gaptooth Ridge','Near the Gaptooth Breach, mine entrance'],
  ['Bone 29','Cholla Springs','Northeast of Armadillo, behind the saloon hill'],
  ['Bone 30','Heartlands','Complete — mail all findings to Deborah MacGuiness'],
];

// ROCK CARVINGS (10) — [name, region, description]
const ROCK_CARVINGS = [
  ['Carving 1','Big Valley',"Northwest of Strawberry near Francis Sinclair\'s cabin"],
  ['Carving 2','Grizzlies East','Near the Barrow Lagoon, rocky cliff face'],
  ['Carving 3','Grizzlies East','North of Moonstone Pond, stone outcrop'],
  ['Carving 4','Grizzlies West','Near Mount Hagen, high altitude cliff'],
  ['Carving 5','Cumberland Forest','South of Bacchus Station, carved boulder'],
  ['Carving 6','Roanoke Ridge','Near the Roanoke Valley, riverside cliff'],
  ['Carving 7','Cholla Springs','East of Lake Don Julio, canyon wall'],
  ['Carving 8','Hennigans Stead','Rocky hillside near the old farmstead'],
  ['Carving 9','Rio Bravo','Near Manteca Falls, carved stone face'],
  ['Carving 10','Tall Trees','Northeast of Manzanita Post, forested cliff'],
];

// DREAMCATCHERS (20) — [name, region, description]
const DREAMCATCHERS = [
  ['Dreamcatcher 1','Roanoke Ridge','Tree near Annesburg, northeast of town'],
  ['Dreamcatcher 2','Roanoke Ridge','Near Brandywine Drop, cliff-side tree'],
  ['Dreamcatcher 3','Roanoke Ridge','Southwest of Van Horn, forest tree'],
  ['Dreamcatcher 4','Cumberland Forest','Near Bacchus Station, pine tree'],
  ['Dreamcatcher 5','Cumberland Forest','West of Emerald Ranch, large oak'],
  ['Dreamcatcher 6','Heartlands','Near Flatneck Station, lone tree'],
  ['Dreamcatcher 7','Heartlands','East of Dewberry Creek, tree cluster'],
  ['Dreamcatcher 8','Grizzlies East','Near Moonstone Pond, birch tree'],
  ['Dreamcatcher 9','Grizzlies East','South of Barrow Lagoon, pine'],
  ['Dreamcatcher 10','Big Valley','Near Little Creek River, willow tree'],
  ['Dreamcatcher 11','Big Valley','Southwest of Strawberry, forest path'],
  ['Dreamcatcher 12','Tall Trees','Near Nekoti Rock, tall pine'],
  ['Dreamcatcher 13','Tall Trees','South of Aurora Basin, tree grove'],
  ['Dreamcatcher 14','Great Plains',"Near Bard\'s Crossing, cottonwood"],
  ['Dreamcatcher 15','Bayou Nwa','Near Shady Belle, cypress tree'],
  ['Dreamcatcher 16','Bayou Nwa','East of Lagras, swamp oak'],
  ['Dreamcatcher 17','Bluewater Marsh','Near Caliga Hall, large tree'],
  ['Dreamcatcher 18','Scarlett Meadows','Near Flat Iron Lake shore, pine'],
  ['Dreamcatcher 19','Lemoyne','Northeast of Rhodes, roadside tree'],
  ['Dreamcatcher 20','Heartlands','Reward: Ancient Arrowhead hidden treasure'],
];

// GRAVES (9) — fallen companions
const GRAVES = [
  ['Davey Callender','Epilogue — Near Chez Porter, Ambarino'],
  ['Jenny Kirk','Epilogue — Near Chez Porter, Ambarino'],
  ['Mac Callender','Epilogue — South of Hanging Dog Ranch, West Elizabeth'],
  ['Kieran Duffy','Epilogue — South of Hanging Dog Ranch, West Elizabeth'],
  ['Sean MacGuire','Epilogue — North of Rhodes, Lemoyne'],
  ['Lenny Summers','Epilogue — North of Rhodes, Lemoyne'],
  ['Susan Grimshaw','Epilogue — North of Beaver Hollow, Roanoke Ridge'],
  ['Hosea Matthews','Epilogue — Saint Denis Cemetery, Lemoyne'],
  ['Arthur Morgan','Epilogue — Cairn Lake or overlooking Donner Falls (honor dependent)'],
];

// HUNTING REQUESTS (5 request lists)
const HUNTING_REQUESTS = [
  {list:'Request 1 (Poster at Train Station)', animals:[
    ['Oriole Carcass (Perfect)','Baltimore or Hooded Oriole'],
    ['Woodpecker Carcass (Perfect)','Red-Bellied or Pileated Woodpecker'],
    ['Robin Carcass (Perfect)','American Robin'],
  ]},
  {list:'Request 2 (via Mail)', animals:[
    ['Squirrel Carcass (Perfect)','Eastern Gray Squirrel'],
    ['Chipmunk Carcass (Perfect)','Western Chipmunk'],
    ['Rat Carcass (Perfect)','Norway Rat'],
    ['Toad Carcass (Perfect)','American Bullfrog'],
  ]},
  {list:'Request 3 (via Mail)', animals:[
    ['Cardinal Carcass (Perfect)','Northern Cardinal'],
    ['Blue Jay Carcass (Perfect)','Blue Jay'],
    ['Bluegill (Perfect)','Bluegill Fish'],
  ]},
  {list:'Request 4 (via Mail)', animals:[
    ['Bat Carcass (Perfect)','Little Brown Bat'],
    ['Opossum Carcass (Perfect)','Virginia Opossum'],
    ['Bullfrog Carcass (Perfect)','American Bullfrog'],
  ]},
  {list:'Request 5 (Epilogue — via Mail)', animals:[
    ['Iguana Skin (Perfect)','Green or Desert Iguana'],
    ['Skunk Pelt (Perfect)','Striped Skunk'],
    ['Snapping Turtle (Perfect)','Common Snapping Turtle'],
    ['Heron Carcass (Perfect)','Great Blue Heron'],
  ]},
];

// EXOTICS — Algernon Wasp requests (6 total)
const EXOTICS = [
  {req:"Request 1",items:[
    ['Lady Slipper Orchid (x5)','Found in Bayou Nwa swamps'],
    ["Acuna\'s Star Orchid (x5)",'Found in Bayou Nwa and Lemoyne'],
    ['Ghost Orchid (x5)','Found in Bayou Nwa, rare'],
    ['Heron Plume (x3)','From Great Blue or Tricolored Heron'],
    ['Egret Feather (x3)','From Snowy, Little, or Reddish Egret'],
    ['Spoonbill Feather (x5)','From Roseate Spoonbill'],
  ]},
  {req:"Request 2",items:[
    ['Night-Scented Orchid (x5)','Found in Bayou Nwa'],
    ["Queen\'s Orchid (x5)",'Found in Bayou Nwa'],
    ['Moccasin Flower Orchid (x5)','Found in Roanoke Ridge'],
    ['Rat Tail Orchid (x5)','Found in Bayou Nwa'],
    ['Crow Feather (x3)','From American Crow'],
    ['Raven Feather (x3)','From Common Raven'],
    ['Vulture Feather (x3)','From Turkey Vulture'],
  ]},
  {req:"Request 3",items:[
    ["Dragon\'s Mouth Orchid (x5)",'Found in Grizzlies'],
    ['Lady of the Night Orchid (x5)','Found in Bayou Nwa'],
    ['Sparrow Hawk Feather (x3)',"From Cooper\'s Hawk or similar"],
    ['Eagle Feather (x3)','From Bald or Golden Eagle'],
    ['Oriole Feather (x3)','From Baltimore or Hooded Oriole'],
  ]},
  {req:"Request 4",items:[
    ['Cigar Orchid (x5)','Found in Bayou Nwa'],
    ['Clamshell Orchid (x5)','Found in Bayou Nwa'],
    ['Spider Orchid (x5)','Found in Bayou Nwa'],
    ['Parrot Feather (x5)','From Blue & Yellow or Scarlet Macaw'],
    ['Peacock Feather (x3)','From Peacock (Saint Denis area)'],
  ]},
  {req:"Request 5",items:[
    ["Sparrow\'s Egg Orchid (x5)",'Found in Tall Trees / Big Valley'],
    ['Lady Slipper Orchid x5 (repeat)','Second batch required'],
    ['Condor Egg (x1)','From Californian Condor nest, Flat Iron Lake'],
  ]},
  {req:"Request 6 — Final",items:[
    ['All prior requests complete','Deliver final items to Algernon Wasp'],
    ["Reward: Algernon\'s Revolver + Exotic Hat + $200",''],
  ]},
];

// TREASURE HUNTS — for 100% completion need 1, track all
const TREASURES = [
  {name:'Jack Hall Gang',clues:['Map found on Flaco Hernandez or purchased from stranger near Flatneck Station',"Treasure 1: Caliban's Seat, Cumberland Forest",'Treasure 2: Cotorra Springs, Ambarino',"Final: O'Creagh's Run island"]},
  {name:'Poisonous Trail',clues:['Map near Cairn Lake, Grizzlies','Treasure 1: West of Window Rock','Treasure 2: Elysian Pool island','Final: East of Annesburg, cliff shelf']},
  {name:'High Stakes',clues:['Map from a stranger near Fort Wallace','Treasure 1: West of Horseshoe Overlook','Treasure 2: Hanging Dog Ranch cliff','Final: Near Bacchus Bridge, Ambarino']},
  {name:'Landmarks of Riches',clues:['Map from lockbox east of Elysian Pool','Treasure 1: Donner Falls','Treasure 2: Bacchus Station bridge','Final: Mount Shann summit']},
  {name:'Elemental Trail',clues:['Map from cave painting near Roanoke Ridge','Treasure 1: Fire (near burning settlement)','Treasure 2: Water (river cave)','Final: Ancient Arrowhead — after all 20 Dreamcatchers']},
];
