
// ═══════════════════ DATA ═══════════════════

// ANIMALS: [group, name, tracked, killed, skinned, studied]  true=checkbox, '-'=N/A
const AN = [
  ['ALLIGATORS','American Alligator',1,1,1,1],
  ['ALLIGATORS','American Alligator (Small)',1,1,1,1],
  ['ARMADILLO','Nine-Banded Armadillo',1,1,1,1],
  ['BADGER','American Badger',1,1,1,1],
  ['BAT','Little Brown Bat',1,1,1,1],
  ['BEARS','American Black Bear',1,1,1,1],
  ['BEARS','Grizzly Bear',1,1,1,1],
  ['BEAVER','North American Beaver',1,1,1,1],
  ['BLUE JAY','Blue Jay',0,1,1,1],
  ['BOAR','Wild Boar',1,1,1,1],
  ['DEER','Whitetail Buck',1,1,1,1],
  ['DEER','Whitetail Deer',1,1,1,1],
  ['BISON','American Bison',1,1,1,1],
  ['BULLS','Angus Bull',0,0,0,1],
  ['BULLS','Devon Bull',0,0,0,1],
  ['BULLS','Hereford Bull',0,0,0,1],
  ['BULLFROG','American Bullfrog',1,1,1,1],
  ['CARDINAL','Northern Cardinal',0,1,1,1],
  ['CAT','American Domestic Cat',0,0,0,1],
  ['WAXWING','Cedar Waxwing',0,1,1,1],
  ['CHICKENS','Dominique Chicken',0,0,0,1],
  ['CHICKENS','Dominique Rooster',0,0,0,1],
  ['CHICKENS','Java Chicken',0,0,0,1],
  ['CHICKENS','Java Rooster',0,0,0,1],
  ['CHICKENS','Leghorn Chicken',0,0,0,1],
  ['CHICKENS','Leghorn Rooster',0,0,0,1],
  ['CHICKENS','Greater Prairie Chicken',0,0,0,1],
  ['CHIPMUNK','Western Chipmunk',1,1,1,1],
  ['CONDOR','Californian Condor',0,1,1,1],
  ['COUGAR','Cougar',1,1,1,1],
  ['CORMORANT','Double-Crested Cormorant',0,1,1,1],
  ['CORMORANT','Neotropic Cormorant',0,1,1,1],
  ['COW','Florida Cracker Cow',0,0,0,1],
  ['COYOTE','California Valley Coyote',1,1,1,1],
  ['CRAB','Cuban Land Crab',1,1,1,1],
  ['CRAYFISH','Red Swamp Crayfish',0,0,1,1],
  ['CRANES','Whooping Crane',0,1,1,1],
  ['CRANES','Sandhill Crane',0,1,1,1],
  ['CROW','American Crow',0,1,1,1],
  ['DOGS','American Fox Hound',0,0,0,1],
  ['DOGS','Australian Shepherd',0,0,0,1],
  ['DOGS','Bloodhound',0,0,0,1],
  ['DOGS','Bluetick Coonhound',0,0,0,1],
  ['DOGS','Border Collie',0,0,0,1],
  ['DOGS','Catahoula Cur',0,0,0,1],
  ['DOGS','Chesapeake Bay Retriever',0,0,0,1],
  ['DOGS','Siberian Husky',0,0,0,1],
  ['DOGS','Labrador Retriever',0,0,0,1],
  ['DOGS','Poodle',0,0,0,1],
  ['DOGS','Mutt',0,0,0,1],
  ['DOGS','Rufus',0,0,0,1],
  ['DONKEY','Standard Donkey',0,0,0,1],
  ['DUCKS','Mallard Duck',0,1,1,1],
  ['DUCKS','Pekin Duck',0,1,1,1],
  ['EAGLES','Bald Eagle',0,1,1,1],
  ['EAGLES','Golden Eagle',0,1,1,1],
  ['EGRETS','Reddish Egret',0,1,1,1],
  ['EGRETS','Little Egret',0,1,1,1],
  ['EGRETS','Snowy Egret',0,1,1,1],
  ['ELKS','Rocky Mountain Bull Elk',1,1,1,1],
  ['ELKS','Rocky Mountain Cow Elk',1,1,1,1],
  ['FOXES','American Red Fox',1,1,1,1],
  ['FOXES','American Gray Fox',1,1,1,1],
  ['FOXES','Silver Fox',1,1,1,1],
  ['GILA MONSTER','Banded Gila Monster',1,1,1,1],
  ['GOATS','Alpine Goat',0,0,0,1],
  ['GOOSE','Canada Goose',0,1,1,1],
  ['HAWKS','Ferruginous Hawk',0,1,1,1],
  ['HAWKS','Red-Tailed Hawk',0,1,1,1],
  ['HAWKS','Rough-Legged Hawk',0,1,1,1],
  ['HERON','Great Blue Heron',0,1,1,1],
  ['HERON','Tricolored Heron',0,1,1,1],
  ['IGUANA','Desert Iguana',1,1,1,1],
  ['IGUANA','Green Iguana',1,1,1,1],
  ['PECCARY','Collared Peccary',1,1,1,1],
  ['LOONS','Common Loon',0,1,1,1],
  ['LOONS','Pacific Loon',0,1,1,1],
  ['LOONS','Yellow-Billed Loon',0,1,1,1],
  ['MOOSE','Western Bull Moose',1,1,1,1],
  ['MOOSE','Western Moose',1,1,1,1],
  ['MULE','Mule',0,0,0,1],
  ['MUSKRAT','American Muskrat',1,1,1,1],
  ['ORIOLES','Baltimore Oriole',0,1,1,1],
  ['ORIOLES','Hooded Oriole',0,1,1,1],
  ['OWLS','Californian Horned Owl',0,1,1,1],
  ['OWLS','Coastal Horned Owl',0,1,1,1],
  ['OWLS','Great Horned Owl',0,1,1,1],
  ['OXEN','Angus Ox',0,0,0,1],
  ['OXEN','Devon Ox',0,0,0,1],
  ['PANTHERS','Panther',1,1,1,1],
  ['PANTHERS','Florida Panther',1,1,1,1],
  ['PARAKEET','Carolina Parakeet',0,1,1,1],
  ['PARROTS','Blue & Yellow Macaw',0,1,1,1],
  ['PARROTS','Great Green Macaw',0,1,1,1],
  ['PARROTS','Scarlet Macaw',0,1,1,1],
  ['PELICANS','American White Pelican',0,1,1,1],
  ['PELICANS','Brown Pelican',0,1,1,1],
  ['PHEASANTS','Ring-Necked Pheasant',0,1,1,1],
  ['PHEASANTS','Chinese Ring-Necked Pheasant',0,1,1,1],
  ['PIGS','Berkshire Pig',0,0,0,1],
  ['PIGS','Big China Pig',0,0,0,1],
  ['PIGS','Old Spot Pig',0,0,0,1],
  ['PIGEONS','Band-Tailed Pigeon',0,1,1,1],
  ['PIGEONS','Rock Pigeon',0,1,1,1],
  ['OPOSSUM','Virginia Opossum',1,1,1,1],
  ['PRONGHORNS','American Pronghorn Buck',1,1,1,1],
  ['PRONGHORNS','American Pronghorn Doe',1,1,1,1],
  ['PRONGHORNS','Sonoran Pronghorn Buck',1,1,1,1],
  ['PRONGHORNS','Sonoran Pronghorn Doe',1,1,1,1],
  ['PRONGHORNS','Baja California Pronghorn Buck',1,1,1,1],
  ['PRONGHORNS','Baja California Pronghorn Doe',1,1,1,1],
  ['QUAIL','California Quail',1,1,1,1],
  ['RAMS','Sierra Nevada Bighorn Ram',1,1,1,1],
  ['RAMS','Sierra Nevada Bighorn Sheep',1,1,1,1],
  ['RAMS','Desert Bighorn Ram',1,1,1,1],
  ['RAMS','Desert Bighorn Sheep',1,1,1,1],
  ['RAMS','Rocky Mountain Bighorn Ram',1,1,1,1],
  ['RAMS','Rocky Mountain Bighorn Sheep',1,1,1,1],
  ['JACKRABBIT','Black-Tailed Jackrabbit',1,1,1,1],
  ['JACKRABBIT','Desert Cottontail',1,1,1,1],
  ['RACCOON','Common Raccoon',1,1,1,1],
  ['RATTLESNAKE','Western Diamondback Rattlesnake',1,1,1,1],
  ['ROBIN','American Robin',0,1,1,1],
  ['SHEEP','Domestic Sheep',0,0,0,1],
  ['SKUNK','Striped Skunk',1,1,1,1],
  ['SNAPPING TURTLE','Common Snapping Turtle',1,0,1,1],
  ['SQUIRREL','Eastern Gray Squirrel',1,1,1,1],
  ['TURKEY','Wild Turkey',0,1,1,1],
  ['VULTURE','Turkey Vulture',0,1,1,1],
  ['WOLF','Gray Wolf',1,1,1,1],
  ['LEGENDARY','Legendary Alligator',1,1,1,1],
  ['LEGENDARY','Legendary Bear',1,1,1,1],
  ['LEGENDARY','Legendary Beaver',1,1,1,1],
  ['LEGENDARY','Legendary Bison',1,1,1,1],
  ['LEGENDARY','Legendary Boar',1,1,1,1],
  ['LEGENDARY','Legendary Buck',1,1,1,1],
  ['LEGENDARY','Legendary Cougar',1,1,1,1],
  ['LEGENDARY','Legendary Coyote',1,1,1,1],
  ['LEGENDARY','Legendary Elk',1,1,1,1],
  ['LEGENDARY','Legendary Fox',1,1,1,1],
  ['LEGENDARY','Legendary Moose',1,1,1,1],
  ['LEGENDARY','Legendary Panther',1,1,1,1],
  ['LEGENDARY','Legendary Pronghorn',1,1,1,1],
  ['LEGENDARY','Legendary Ram',1,1,1,1],
  ['LEGENDARY','Legendary White Bison',1,1,1,1],
  ['LEGENDARY','Legendary Wolf',1,1,1,1],
];
// AN cols: [2]=tracked,[3]=killed,[4]=skinned,[5]=studied
const AN_COLS = ['TRACKED','KILLED','SKINNED','STUDIED'];

// PLANTS: [cat, name, picked, recipe, herbalist]
const PL = [
  ['GINSENG','Alaskan Ginseng',1,1,1],['GINSENG','American Ginseng',1,1,1],
  ['MUSHROOM','Bay Bolete',1,1,1],['BERRY','Blackberry',1,1,1],
  ['CURRANT','Black Currant',1,1,1],['ROOT','Burdock Root',1,1,1],
  ['MUSHROOM','Chanterelles',1,1,1],['GRASS','Common Bulrush',1,1,1],
  ['HERB','Creeping Thyme',1,1,1],['SAGE','Desert Sage',1,1,1],
  ['HERB','English Mace',1,1,1],['BERRY','Evergreen Huckleberry',1,1,1],
  ['CURRANT','Golden Currant',1,1,1],['SAGE','Hummingbird Sage',1,1,1],
  ['HERB','Indian Tobacco',1,1,1],['HERB','Milkweed',1,1,1],
  ['SAGE','Oleander Sage',1,1,1],['HERB','Oregano',1,1,1],
  ['MUSHROOM','Parasol Mushroom',1,1,1],['FLOWER','Prairie Poppy',1,1,1],
  ['MUSHROOM',"Ram's Head",1,1,1],['BERRY','Red Raspberry',1,1,1],
  ['SAGE','Red Sage',1,1,1],['FLOWER','Vanilla Flower',1,1,1],
  ['FLOWER','Violet Snowdrops',1,1,1],['ROOT','Wild Carrot',1,1,1],
  ['HERB','Wild Feverfew',1,1,1],['HERB','Wild Mint',1,1,1],
  ['BERRY','Wintergreen Berry',1,1,1],['HERB','Yarrow',1,1,1],
  ['ORCHID',"Acuna's Star Orchid",1,0,1],['ORCHID','Cigar Orchid',1,0,1],
  ['ORCHID','Clamshell Orchid',1,0,1],['ORCHID',"Dragon's Mouth Orchid",1,0,1],
  ['ORCHID','Ghost Orchid',1,0,1],['ORCHID','Lady of the Night Orchid',1,0,1],
  ['ORCHID','Lady Slipper Orchid',1,0,1],['ORCHID','Moccasin Flower Orchid',1,0,1],
  ['ORCHID','Night Scented Orchid',1,0,1],['ORCHID',"Queen's Orchid",1,0,1],
  ['ORCHID','Rat Tail Orchid',1,0,1],["ORCHID","Sparrow's Egg Orchid",1,0,1],
  ['ORCHID','Spider Orchid',1,0,1],
];
const PL_COLS = ['PICKED','RECIPE','HERBALIST'];

// FISH: [name, caught, baited, survivalist, isLegendary]
const FI = [
  ['Bluegill',1,1,1,0],['Chain Pickerel',1,1,1,0],['Redfin Pickerel',1,1,1,0],
  ['Rock Bass',1,1,1,0],['Smallmouth Bass',1,1,1,0],['Bullhead Catfish',1,1,1,0],
  ['Perch',1,1,1,0],['Lake Sturgeon',1,1,1,0],['Largemouth Bass',1,1,1,0],
  ['Steelhead Trout',1,1,1,0],['Channel Catfish',1,1,1,0],['Longnose Gar',1,1,1,0],
  ['Muskie',1,1,1,0],['Northern Pike',1,1,1,0],['Sockeye Salmon',1,1,1,0],
  ['Legendary Bluegill',1,0,0,1],['Legendary Chain Pickerel',1,0,0,1],
  ['Legendary Bullhead Catfish',1,0,0,1],['Legendary Redfin Pickerel',1,0,0,1],
  ['Legendary Rock Bass',1,0,0,1],['Legendary Smallmouth Bass',1,0,0,1],
  ['Legendary Perch',1,0,0,1],['Legendary Lake Sturgeon',1,0,0,1],
  ['Legendary Largemouth Bass',1,0,0,1],['Legendary Steelhead Trout',1,0,0,1],
  ['Legendary Channel Catfish',1,0,0,1],['Legendary Longnose Gar',1,0,0,1],
  ['Legendary Muskie',1,0,0,1],['Legendary Northern Pike',1,0,0,1],
  ['Legendary Sockeye Salmon',1,0,0,1],
];
const FI_COLS = ['CAUGHT','BAITED','SURVIVALIST'];

// HORSES: [breed, coat, studied, bonded, ridden, horseman]
const HO = [
  ['AMERICAN PAINT','Splashed White',1,1,1,1],['AMERICAN PAINT','Grey Overo',1,1,1,1],
  ['AMERICAN PAINT','Overo',1,1,1,1],['AMERICAN PAINT','Tobiano',1,1,1,1],
  ['AMERICAN STANDARDBRED','Palomino Dapple',1,1,1,1],['AMERICAN STANDARDBRED','Silvertail Buckskin',1,1,1,1],
  ['AMERICAN STANDARDBRED','Buckskin',1,1,1,1],['AMERICAN STANDARDBRED','Black',1,1,1,1],
  ['ANDALUSIAN','Perlino',1,1,1,0],['ANDALUSIAN','Rose Grey',1,1,1,0],['ANDALUSIAN','Dark Bay',1,1,1,0],
  ['APPALOOSA','Few Spotted',1,1,1,1],['APPALOOSA','Brown Leopard',1,1,1,1],
  ['APPALOOSA','Leopard',1,1,1,1],['APPALOOSA','Leopard Blanket',1,1,1,1],['APPALOOSA','Blanket',1,1,1,1],
  ['ARABIAN','White',1,1,1,0],['ARABIAN','Black',1,1,1,0],['ARABIAN','Rose Grey Bay',1,1,1,0],
  ['ARABIAN','Chestnut',1,1,1,0],['ARABIAN','Warped Brindle',1,1,1,0],
  ['ARDENNES','Strawberry Roan',1,1,1,0],['ARDENNES','Bay Roan',1,1,1,0],
  ['BELGIAN DRAFT','Mealy Chestnut',1,1,1,0],['BELGIAN DRAFT','Blonde Chestnut',1,1,1,0],
  ['DUTCH WARMBLOOD','Cremello Gold',1,1,1,0],['DUTCH WARMBLOOD','Chocolate Roan',1,1,1,0],
  ['DUTCH WARMBLOOD','Seal Brown',1,1,1,0],['DUTCH WARMBLOOD','Sooty Buckskin',1,1,1,0],
  ['HUNGARIAN HALFBRED','Dapple Dark Grey',1,1,1,1],['HUNGARIAN HALFBRED','Piebald Tobiano',1,1,1,1],['HUNGARIAN HALFBRED','Flaxen Chestnut',1,1,1,1],
  ['KENTUCKY SADDLER','Grey',1,1,1,1],['KENTUCKY SADDLER','Silver Bay',1,1,1,1],
  ['KENTUCKY SADDLER','Black',1,1,1,1],['KENTUCKY SADDLER','Chestnut Pinto',1,1,1,1],['KENTUCKY SADDLER','Buttermilk Buckskin',1,1,1,1],
  ['MISSOURI FOX TROTTER','Amber Champagne',1,1,1,0],['MISSOURI FOX TROTTER','Silver Dapple Pinto',1,1,1,0],
  ['MORGAN','Bay',1,1,1,1],['MORGAN','Bay Roan',1,1,1,1],['MORGAN','Palomino',1,1,1,1],
  ['MORGAN','Flaxen Chestnut',1,1,1,1],['MORGAN','Liver Chestnut',1,1,1,1],
  ['MUSTANG','Tiger Striped Bay',1,1,1,1],['MUSTANG','Grullo Dun',1,1,1,1],['MUSTANG','Wild Bay',1,1,1,1],
  ['NOKOTA','Reverse Dapple Roan',1,1,1,1],['NOKOTA','Blue Roan',1,1,1,1],['NOKOTA','White Roan',1,1,1,1],
  ['SHIRE','Raven Black',1,1,1,0],['SHIRE','Light Grey',1,1,1,0],['SHIRE','Dark Bay',1,1,1,0],
  ['SUFFOLK PUNCH','Sorrel',1,1,1,0],['SUFFOLK PUNCH','Red Chestnut',1,1,1,0],
  ['TENNESSEE WALKER','Mahogany Bay',1,1,1,1],['TENNESSEE WALKER','Flaxen Roan',1,1,1,1],
  ['TENNESSEE WALKER','Red Roan',1,1,1,1],['TENNESSEE WALKER','Black Rabicano',1,1,1,1],
  ['THOROUGHBRED','Blood Bay',1,1,1,0],['THOROUGHBRED','Dapple Grey',1,1,1,0],['THOROUGHBRED','Brindle',1,1,1,0],
  ['TURKOMAN','Gold',1,1,1,0],['TURKOMAN','Dark Bay',1,1,1,0],['TURKOMAN','Silver',1,1,1,0],
];
const HO_COLS = ['STUDIED','BONDED','RIDDEN','HORSEMAN'];

// WEAPONS: [category, name]
const WE = [
  ['REVOLVERS','Cattleman Revolver'],['REVOLVERS',"Granger's Revolver"],['REVOLVERS',"Flaco's Revolver"],
  ['REVOLVERS',"John's Cattleman Revolver"],['REVOLVERS','Double-Action Revolver'],['REVOLVERS',"Algernon's Revolver"],
  ['REVOLVERS',"Micah's Revolver"],['REVOLVERS','High Roller Revolver'],['REVOLVERS','Schofield Revolver'],
  ['REVOLVERS',"Calloway's Revolver"],['REVOLVERS',"Otis Miller's Revolver"],['REVOLVERS','LeMat Revolver'],
  ['PISTOLS','Volcanic Pistol'],['PISTOLS','Semi-Automatic Pistol'],['PISTOLS','Mauser Pistol'],
  ['PISTOLS',"Midnight's Pistol"],['PISTOLS','M1899 Pistol'],
  ['REPEATERS','Carbine Repeater'],['REPEATERS','Lancaster Repeater'],['REPEATERS','Litchfield Repeater'],['REPEATERS','Evans Repeater'],
  ['RIFLES','Varmint Rifle'],['RIFLES','Springfield Rifle'],['RIFLES','Bolt Action Rifle'],
  ['RIFLES','Rolling Block Rifle'],['RIFLES','Rare Rolling Block Rifle'],['RIFLES','Carcano Rifle'],
  ['SHOTGUNS','Sawed-Off Shotgun'],['SHOTGUNS','Double-Barreled Shotgun'],['SHOTGUNS','Rare Shotgun'],
  ['SHOTGUNS','Pump-Action Shotgun'],['SHOTGUNS','Semi-Auto Shotgun'],['SHOTGUNS','Repeating Shotgun'],
  ['BOW','Bow'],['UNARMED','Unarmed'],
  ['THROWABLES','Fire Bottle'],['THROWABLES','Volatile Fire Bottle'],['THROWABLES','Dynamite'],
  ['THROWABLES','Volatile Dynamite'],['THROWABLES','Throwing Knife'],['THROWABLES','Improved Throwing Knife'],
  ['THROWABLES','Poison Throwing Knife'],['THROWABLES','Tomahawk'],['THROWABLES','Improved Tomahawk'],
  ['THROWABLES','Homing Tomahawk'],['THROWABLES','Ancient Tomahawk'],
  ['MELEE','Cleaver'],['MELEE','Machete'],['MELEE','Broken Pirate Sword'],['MELEE','Hunting Knife'],
  ['MELEE',"John's Knife"],['MELEE','Antler Knife'],['MELEE','Civil War Knife'],['MELEE','Jawbone Knife'],
  ['MELEE','Wide-Blade Knife'],['MELEE','Ornate Dagger'],['MELEE','Hatchet'],['MELEE','Hewing Hatchet'],['MELEE','Viking Hatchet'],
];

// EQUIPMENT: [cat, name, note]
const EQ = [
  ['KIT','Lasso','auto-given'],['KIT','Binoculars','auto-given'],['KIT','Fishing Rod','auto-given'],
  ['KIT','Electric Lantern','"A Bright Bouncing Boy II"'],['KIT','Lantern','auto-given'],['KIT','Camera','auto-given'],
  ['GUN EQUIP','Upgraded Bandolier','purchase at gunsmith'],['GUN EQUIP','Upgraded Gun Belt','purchase at gunsmith'],
  ['GUN EQUIP','Upgraded Holster','purchase at gunsmith'],['GUN EQUIP','Off-Hand Holster','"Blessed Are The Meek?"'],
  ['SATCHELS','Ingredients Satchel','1 deer pelt, 1 badger pelt, 1 squirrel carcass'],
  ['SATCHELS','Materials Satchel','1 deer pelt, 1 boar pelt, 1 iguana skin'],
  ['SATCHELS','Valuables Satchel','1 deer pelt, 1 beaver pelt, 1 rabbit pelt'],
  ['SATCHELS','Tonics Satchel','1 deer pelt, 1 elk pelt, 1 buck pelt'],
  ['SATCHELS','Kit Satchel','1 deer pelt, 1 elk pelt, 1 panther pelt'],
  ['SATCHELS','Provisions Satchel','1 deer pelt, 1 bison pelt, 1 raccoon pelt'],
  ['SATCHELS','Legend of the East Satchel','1 deer pelt, 1 cougar pelt, 1 wolf pelt'],
  ['TALISMANS','Alligator Tooth Talisman','Civil War handcuffs + gold jointed bracelet + Legendary Alligator tooth'],
  ['TALISMANS','Boar Tusk Talisman','gold earring + cobalt petrified wood + Legendary Boar tusk'],
  ['TALISMANS','Bison Horn Talisman','abalone shell fragment + silver earring + Legendary Bison horn'],
  ['TALISMANS','Bear Claw Talisman','silver chain bracelet + quartz chunk + Legendary Bear claw'],
  ['TRINKETS','Tatanka Bison Horn Trinket','Legendary Tatanka Bison horn'],
  ['TRINKETS','Beaver Tooth Trinket','Legendary Beaver tooth'],
  ['TRINKETS','Buck Antler Trinket','Legendary Buck antler'],
  ['TRINKETS','Cougar Fang Trinket','Legendary Cougar fang'],
  ['TRINKETS','Coyote Fang Trinket','Legendary Coyote fang'],
  ['TRINKETS','Elk Antler Trinket','Legendary Elk antler'],
  ['TRINKETS','Fox Claw Trinket','Legendary Fox claw'],
  ['TRINKETS','Moose Antler Trinket','Legendary Moose antler'],
  ['TRINKETS','Owl Feather Trinket','"Archeology for Beginners" — no-kill reward'],
  ['TRINKETS','Pronghorn Horn Trinket','Legendary Pronghorn horn'],
  ['TRINKETS','Ram Horn Trinket','Legendary Ram horn'],
  ['TRINKETS','Raven Claw Talisman','old brass compass'],
  ['TRINKETS','Wolf Heart Trinket','Legendary Wolf heart'],
  ["TRINKETS","Lion's Paw Trinket",'"He\'s British, Of Course IV" — lion\'s paw'],
  ["TRINKETS","Panther's Eye Trinket",'Legendary Panther eye'],
  ['TRINKETS','Shark Tooth Trinket','Roanoke Ridge — lockbox near beached ship'],
  ['TRINKETS','Hawk Talon Trinket','Deadboot Creek — lockbox at destroyed campsite'],
  ['TRINKETS','Cat Eye Trinket','Flat Iron Lake southern island — lockbox'],
  ['TRINKETS','Turtle Shell Trinket','Gaptooth Breach — lockbox under stairs'],
  ['TRINKETS','Crow Beak Trinket','"Elemental Trails" treasure hunt'],
  ['BANDIT GEAR','Bandit Bandolier','Bandit 1 — hold up 5 townsfolk'],
  ['BANDIT GEAR','Bandit Holster','Bandit 3 — rob cash registers in 4 shops in one day'],
  ['BANDIT GEAR','Bandit Off-Hand Holster','Bandit 7 — rob $50 from townsfolk/travelers'],
  ['BANDIT GEAR','Bandit Gun Belt','Bandit 10 — rob 5 trains without dying/caught'],
  ['EXPLORER GEAR','Explorer Holster','Explorer 1 — find a treasure map'],
  ['EXPLORER GEAR','Explorer Bandolier','Explorer 3 — complete a 2nd treasure hunt'],
  ['EXPLORER GEAR','Explorer Gun Belt','Explorer 7 — complete a 6th treasure hunt'],
  ['EXPLORER GEAR','Explorer Off-Hand Holster','Explorer 10 — complete a 9th treasure hunt'],
  ['GAMBLER GEAR','Gambler Holster','Gambler 1 — win 5 hands of poker'],
  ['GAMBLER GEAR','Gambler Bandolier','Gambler 3 — win 3 games of Five Finger Fillet'],
  ['GAMBLER GEAR','Gambler Gun Belt','Gambler 7 — beat Five Finger Fillet in every location'],
  ['GAMBLER GEAR','Gambler Off-Hand Holster','Gambler 10 — win 3 hands of poker in a row'],
  ['HERBALIST GEAR','Herbalist Off-Hand Holster','Herbalist 1 — pick 6 yarrow'],
  ['HERBALIST GEAR','Herbalist Gun Belt','Herbalist 3 — craft 7 items using sage'],
  ['HERBALIST GEAR','Herbalist Holster','Herbalist 7 — craft & use 5 Special Miracle Tonics'],
  ['HERBALIST GEAR','Herbalist Bandolier','Herbalist 10 — season & cook all 11 types of meat'],
  ['HORSEMAN GEAR','Horseman Gun Belt','Horseman 1 — kill 5 rabbits from horseback'],
  ['HORSEMAN GEAR','Horseman Holster','Horseman 3 — ride Valentine to Rhodes in <5 min'],
  ['HORSEMAN GEAR','Horseman Bandolier','Horseman 7 — kill 7 enemies from horseback without dismounting'],
  ['HORSEMAN GEAR','Horseman Off-Hand Holster','Horseman 10 — break every wild horse breed'],
  ['MASTER HUNTER GEAR','Master Hunter Off-Hand Holster','Master Hunter 1 — skin 3 deer'],
  ['MASTER HUNTER GEAR','Master Hunter Bandolier','Master Hunter 3 — track 10 animal species'],
  ['MASTER HUNTER GEAR','Master Hunter Gun Belt','Master Hunter 7 — use bait to lure & kill herbivore and predator'],
  ['MASTER HUNTER GEAR','Master Hunter Holster','Master Hunter 10 — kill all legendary animals'],
  ['SHARPSHOOTER GEAR','Sharpshooter Off-Hand Holster','Sharpshooter 1 — get 10 headshot kills'],
  ['SHARPSHOOTER GEAR','Sharpshooter Bandolier','Sharpshooter 3 — kill someone 80+ ft away with throwing knife'],
  ['SHARPSHOOTER GEAR','Sharpshooter Gun Belt','Sharpshooter 7 — kill 3 enemies in 10 seconds with bow'],
  ['SHARPSHOOTER GEAR','Sharpshooter Holster','Sharpshooter 10 — kill 3 flying birds with 3 consecutive shots'],
  ['SURVIVALIST GEAR','Survivalist Off-Hand Holster','Survivalist 1 — craft 9 items at camp/wild'],
  ['SURVIVALIST GEAR','Survivalist Bandolier','Survivalist 3 — cook a flattened bread recipe'],
  ['SURVIVALIST GEAR','Survivalist Gun Belt','Survivalist 7 — craft a Special Miracle Tonic'],
  ['SURVIVALIST GEAR','Survivalist Holster','Survivalist 10 — craft every type of arrow'],
  ['TREASURE HUNTER GEAR','Treasure Hunter Off-Hand Holster','Treasure Hunter 1 — find treasure map on bounty'],
  ['TREASURE HUNTER GEAR','Treasure Hunter Bandolier','Treasure Hunter 3 — find a treasure'],
  ['TREASURE HUNTER GEAR','Treasure Hunter Gun Belt','Treasure Hunter 7 — find treasure map on a soldier'],
  ['TREASURE HUNTER GEAR','Treasure Hunter Holster','Treasure Hunter 10 — complete Jack Hall, Poisonous Trail & High Stakes maps'],
];

// TRAPPER: [cat, name, materials]
const TR = [
  ['HATS','Badger Mountain Hat','Badger pelt'],
  ['HATS','Bear Grenadier Hat','Perfect Bear pelt'],
  ['HATS','Beaver Mountain Hat','Perfect Beaver pelt'],
  ["HATS","Bison Gambler's Hat",'Perfect Bison pelt'],
  ['HATS','Deer Cavalry Hat','Perfect Deer pelt'],
  ['HATS','Fox Mountain Hat','Perfect Fox pelt'],
  ["HATS","Gila Monster Gambler's Hat",'Perfect Gila Monster skin'],
  ['HATS','Iguana Big Valley Hat','Perfect Iguana skin'],
  ['HATS','Pronghorn Flop Hat','Perfect Pronghorn hide'],
  ['HATS','Rat Flat Cap','Perfect Rat skin x2'],
  ['HATS','Rat Infantry Hardee Hat','Perfect Rat skin x2'],
  ['HATS','Skunk Mountain Hat','Perfect Skunk pelt'],
  ['HATS','Snake Bulldogger Hat','Perfect Snake skin'],
  ['HATS','Squirrel Flat Cap','Perfect Squirrel pelt'],
  ['ACCESSORIES','Glorious Accessory','Perfect Turkey feather x3 + Perfect Raven feather x2'],
  ['ACCESSORIES','Homestead Accessory','Perfect Goose feather x2 + Perfect Robin feather x2'],
  ['ACCESSORIES','Huntsman Accessory','Perfect Pheasant feather x2 + Perfect Hawk feather'],
  ['ACCESSORIES','Judicious Accessory','Perfect Duck feather x2 + Perfect Eagle feather'],
  ['ACCESSORIES','Majestic Accessory','Perfect Cardinal feather x2 + Perfect Robin feather x2'],
  ['ACCESSORIES','Native Accessory','Perfect Chicken feather x2 + Perfect Loon feather x2'],
  ['ACCESSORIES','Pilgrim Accessory','Perfect Condor feather + Perfect Pigeon feather'],
  ['ACCESSORIES','Pioneer Accessory','Perfect Crow feather + Perfect Songbird feather'],
  ['ACCESSORIES','Pursuer Accessory','Perfect Hawk feather x2 + Perfect Cedar Waxwing feather x2'],
  ['ACCESSORIES','Rococo Accessory','Perfect Quail feather + Perfect Blue Jay feather'],
  ['ACCESSORIES','Scavenger Accessory','Perfect Vulture feather + Perfect Pigeon feather'],
  ['ACCESSORIES','Stalker Accessory','Perfect Sparrow feather x3 + Perfect Oriole feather'],
  ['VESTS','Hinterland Vest','Perfect Loon feather x2 + Perfect Elk pelt'],
  ['VESTS','Rugged Wrangler Vest','Perfect Oriole feather x3 + Perfect Goose feather'],
  ['VESTS','Rustic Vest','Perfect Owl feather + Perfect Pheasant feather x2'],
  ['CHAPS','Batwing Chaps','Perfect Opossum pelt + Perfect Muskrat pelt'],
  ['CHAPS','Bear Batwing Chaps','Perfect Bear pelt + Perfect Bison pelt'],
  ['CHAPS','Bear Fringed Shotgun Chaps','Perfect Bear pelt + Perfect Squirrel pelt'],
  ['CHAPS','Deer Pelt Half Chaps','Perfect Deer pelt x2'],
  ['CHAPS','Elk Fringed Shotgun Chaps','Perfect Elk pelt + Perfect Rabbit pelt'],
  ['CHAPS','Moose Batwing Chaps','Perfect Moose pelt + Perfect Sheep hide'],
  ['CHAPS','Muskrat Half Chaps','Perfect Muskrat pelt x3'],
  ['CHAPS','Ox Fringed Shotgun Chaps','Perfect Ox hide + Perfect Rabbit pelt'],
  ['CHAPS','Sheep Batwing Chaps','Perfect Sheep hide x2'],
  ['BOOTS','Javelina Moccasins','Perfect Collared Peccary pelt x2'],
  ['BOOTS','Moccasins','Perfect Boar pelt + Perfect Ram hide'],
  ['BOOTS','Skunk Trapper Boots','Perfect Skunk pelt x2 + Perfect Rabbit pelt'],
  ['SADDLES','Alligator Ranch Cutter','Perfect Alligator skin'],
  ['SADDLES','Bear Dakota','Perfect Bear pelt'],
  ['SADDLES','Beaver Roping','Perfect Beaver pelt x2'],
  ['SADDLES','Boar Mother Hubbard','Perfect Boar pelt x2'],
  ['SADDLES','Cougar McClelland','Perfect Cougar pelt'],
  ['SADDLES','Panther Trail','Perfect Panther pelt'],
  ['SADDLES','Rattlesnake Vaquero','Perfect Snake skin x2'],
  ['LEGENDARY — HATS','Legendary Cougar Flop Hat','Legendary Cougar pelt + Perfect Fox pelt'],
  ['LEGENDARY — HATS','Legendary Fox Fur Cap','Legendary Fox pelt + Perfect Rabbit pelt'],
  ['LEGENDARY — HATS','Legendary Ram Hat','Legendary Ram hide + Perfect Boar pelt'],
  ['LEGENDARY — HATS','Legendary Beaver Flop Hat','Legendary Beaver pelt + Perfect Rabbit pelt'],
  ['LEGENDARY — COATS','Legendary Bear Coat','Legendary Bear pelt + Perfect Bull hide'],
  ['LEGENDARY — COATS','Legendary Moose Safari Jacket','Legendary Moose pelt + Perfect Deer pelt'],
  ['LEGENDARY — COATS','Legendary Wolf Batwing Coat','Legendary Wolf pelt + Perfect Coyote pelt'],
  ['LEGENDARY — COATS','Legendary Ram Rifleman Coat','Legendary Ram hide + Perfect Boar pelt'],
  ['LEGENDARY — VESTS','Legendary Buck Vest','Legendary Buck antler + Perfect Deer pelt'],
  ['LEGENDARY — VESTS','Legendary Boar Vest','Legendary Boar tusk + Perfect Pig skin'],
  ['LEGENDARY — VESTS','Legendary Elk Vest','Legendary Elk antler + Perfect Deer pelt'],
  ['LEGENDARY — VESTS','Legendary Panther Cloak','Legendary Panther eye + Perfect Cougar pelt'],
  ['LEGENDARY — VESTS','Legendary Tatanka Bison Vest','Legendary Tatanka Bison horn + Perfect Bull hide'],
  ['LEGENDARY — VESTS','Legendary Pronghorn Vest','Legendary Pronghorn horn + Perfect Deer pelt'],
  ['LEGENDARY — VESTS','Legendary Alligator Vest & Fowlers','Legendary Alligator skin + Perfect Deer pelt'],
  ['LEGENDARY — GLOVES','Legendary Bear Roper','Legendary Bear claw + Perfect Deer pelt'],
  ['LEGENDARY — GLOVES','Legendary Boar Riding Gloves','Legendary Boar tusk + Perfect Pig skin'],
  ['LEGENDARY — GLOVES','Legendary Elk Range Gloves','Legendary Elk antler + Perfect Deer pelt'],
  ['LEGENDARY — GLOVES','Legendary Cougar Riding Gloves','Legendary Cougar fang + Perfect Deer pelt'],
  ['LEGENDARY — GLOVES','Legendary Fox Moccasins','Legendary Fox claw + Perfect Rabbit pelt'],
  ['LEGENDARY — GLOVES','Legendary Moose Riding Gloves','Legendary Moose antler + Perfect Deer pelt'],
  ['LEGENDARY — GLOVES','Legendary Wolf Batwing Chaps','Legendary Wolf heart + Perfect Coyote pelt'],
  ['OUTFITS','Rattler (Ram Sombrero, Outdoorsman Vest, Javelina Half Chaps, Iguana Range Gloves)','Various pelts — see individual pieces'],
  ['OUTFITS','Wrangler (Goat Flop Hat, Trapper Cloak, No Man\'s Vest, Two Toned Moccasins)','Various pelts'],
  ['OUTFITS','Bronco Buster (Elk Flop Hat, Coyote Scout Jacket, Huntsman Vest, Boar Fringed Shotgun Chaps)','Various pelts'],
  ['OUTFITS','Marauder (Muskrat Cavalry Hat, Principal Vest, Bull Fringed Shotgun Chaps, Snakeskin Cavalry Gloves)','Various pelts'],
  ['OUTFITS','Bounty Hunter (Plantation Slouch Hat, Beaver Hunting Jacket, Sheepskin Vest, Pronghorn Half Chaps)','Various pelts'],
  ['OUTFITS','Desperado (Beaver Drifter Hat, Wolf Coat, Billy Vest, Boar & Bull Fowler Boots)','Various pelts'],
  ['OUTFITS','Night Wrangler (Coyote Gambler\'s Hat, Cougar Cutaway Coat, Wilderness Vest, Moose Half Chaps)','Various pelts'],
  ['OUTFITS','Mountain Man (Grenadier Hat, Ram Shotgun Coat, Country Vest, Elk Riding Gloves)','Various pelts'],
];

// PEARSON: [cat, name, materials]
const PE = [
  ["ARTHUR'S AREA",'Alligator Skull','Alligator skin'],
  ["ARTHUR'S AREA",'Big Horn Ram Skull','Ram carcass'],
  ["ARTHUR'S AREA",'Cougar Pelt Covered Chest','Cougar pelt x2'],
  ["ARTHUR'S AREA",'Boar Skin Table Cover','Boar pelt'],
  ["ARTHUR'S AREA",'Ox Hide Rug','Ox hide x2'],
  ["JOHN'S AREA","Boar Skin Rug",'Boar pelt x4'],
  ['CAMP TABLE','Pronghorn Leather Table Tops','Pronghorn hide x2'],
  ['WAGON','Pronghorn Skull','Pronghorn carcass'],
  ['CAMPFIRE','Moose Antlers','Moose antler'],
  ['CAMPFIRE','Wolf Skull','Wolf carcass'],
  ['CAMPFIRE','Snake Skin Banjo Head','Snake skin x2'],
  ['CAMPFIRE','Campfire Seat Cover','Beaver pelt + Muskrat pelt + Fox pelt'],
  ['CAMPFIRE','Campfire Log Seat Cover','Wolf pelt x2'],
  ['CAMPFIRE','Lean-To Cowhide Ground Cover','Cow hide'],
  ['SCOUT FIRE','Scout Fire Ground Cover','Goat hide x2'],
  ['SCOUT FIRE','Elk Antlers','Elk antler'],
  ['SCOUT FIRE','Hanging Bones','Buck antler'],
];

// CHALLENGES: [set, [[level, requirement, reward], ...]]
const CH = {
  'BANDIT':[
    ['Level 1','Hold Up 5 Townsfolk','Bandit Bandolier'],
    ['Level 2','Rob Two Coaches (Missions or Road)','$5 / 25 Dead Eye XP'],
    ['Level 3','Rob Cash Register in 4 Shops in One Day','Bandit Holster'],
    ['Level 4','Rob Three Coaches in One Day','$10 / 50 Dead Eye XP'],
    ['Level 5','Amass $250 Bounty in One State','$10 / 50 Dead Eye XP'],
    ['Level 6','Steal 5 Horses & Sell to Horse Fence','$15 / 100 Dead Eye XP'],
    ['Level 7','Rob $50 Worth of Cash/Valuables from Townsfolk or Travelers','Bandit Off-Hand Holster'],
    ['Level 8','Steal 7 Wagons & Sell to Fence at Emerald Ranch','$15 / 100 Dead Eye XP'],
    ['Level 9','Hogtie Someone & Leave on Railroad 3 Times','$20 / 150 Dead Eye XP'],
    ['Level 10','Rob 5 Trains Without Dying or Being Caught','Bandit Gun Belt'],
  ],
  'EXPLORER':[
    ['Level 1','Find a Treasure Map','Explorer Holster'],
    ['Level 2','Find a Treasure','$5 / 25 Stamina XP'],
    ['Level 3','Find a Treasure','Explorer Bandolier'],
    ['Level 4','Find a Treasure','$10 / 50 Stamina XP'],
    ['Level 5','Find a Treasure','$10 / 50 Stamina XP'],
    ['Level 6','Find a Treasure','$15 / 100 Stamina XP'],
    ['Level 7','Find a Treasure','Explorer Gun Belt'],
    ['Level 8','Find a Treasure','$15 / 100 Stamina XP'],
    ['Level 9','Find a Treasure','$20 / 150 Stamina XP'],
    ['Level 10','Find a Treasure','Explorer Off-Hand Holster'],
  ],
  'GAMBLER':[
    ['Level 1','Win Five Hands of Poker','Gambler Holster'],
    ['Level 2','In Blackjack, Double Down and Win the Hand 5 Times','$5 / 25 Dead Eye XP'],
    ['Level 3','Win Three Games of Five Finger Fillet','Gambler Bandolier'],
    ['Level 4','Bust One Poker Opponent Out in Flatneck, Saint Denis & Valentine','$10 / 50 Dead Eye XP'],
    ['Level 5','Win 3 Rounds of Dominoes Without Drawing Tiles vs 2 or Fewer Opponents','$10 / 50 Dead Eye XP'],
    ['Level 6','Beat Blackjack Dealer in Rhodes and Van Horn','$15 / 100 Dead Eye XP'],
    ['Level 7','Beat Five Finger Fillet in Strawberry, Valentine, and Van Horn','Gambler Gun Belt'],
    ['Level 8','Win 3 Hands of Blackjack With 3+ Hits','$15 / 100 Dead Eye XP'],
    ['Level 9','Win Three Games of Dominoes in a Row','$20 / 150 Dead Eye XP'],
    ['Level 10','Win Three Hands of Poker in a Row','Gambler Off-Hand Holster'],
  ],
  'HERBALIST':[
    ['Level 1','Pick Six Yarrow','Herbalist Off-Hand Holster'],
    ['Level 2','Pick and Eat Four Species of Berry','$5 / 25 Health XP'],
    ['Level 3','Craft Seven Items Using Sage as an Ingredient','Herbalist Gun Belt'],
    ['Level 4','Pick Five Mushrooms and Feed Them to Your Horse','$10 / 50 Health XP'],
    ['Level 5','Craft Nine Items Using Indian Tobacco as an Ingredient','$10 / 50 Health XP'],
    ['Level 6','Pick 15 Different Species of Herbs','$15 / 100 Health XP'],
    ['Level 7','Craft and Use Five Special Miracle Tonics','Herbalist Holster'],
    ['Level 8','Use Oleander to Craft Six Poison Weapons','$15 / 100 Health XP'],
    ['Level 9','Pick One of Each Species of Herb','$20 / 150 Health XP'],
    ['Level 10','Season and Cook All Eleven Types of Meat','Herbalist Bandolier'],
  ],
  'HORSEMAN':[
    ['Level 1','Kill Five Rabbits from Horseback','Horseman Gun Belt'],
    ['Level 2','Jump Over Three Obstacles in 15 Seconds','$5 / 25 Stamina XP'],
    ['Level 3','Ride Valentine to Rhodes in Less Than 5 Minutes','Horseman Holster'],
    ['Level 4','While Mounted, Drag a Victim 3,300 Feet Using Your Lasso','$10 / 50 Stamina XP'],
    ['Level 5','Trample Five Animals While on Horseback','$10 / 50 Stamina XP'],
    ['Level 6','Ride Strawberry to Saint Denis in Under 9 Minutes Without Touching Water','$15 / 100 Stamina XP'],
    ['Level 7','Kill Seven Enemies From Horseback Without Dismounting','Horseman Bandolier'],
    ['Level 8','Kill Nine Predators From Horseback','$15 / 100 Stamina XP'],
    ['Level 9','Ride Van Horn to Blackwater in Under 17 Minutes Without Touching Water','$20 / 150 Stamina XP'],
    ['Level 10','Break Every Wild Horse Breed','Horseman Off-Hand Holster'],
  ],
  'MASTER HUNTER':[
    ['Level 1','Skin Three Deer','Master Hunter Off-Hand Holster'],
    ['Level 2','Get Three Perfect-Quality Rabbit Pelts','$5 / 25 Health XP'],
    ['Level 3','Track 10 Different Animal Species Using Your Binoculars','Master Hunter Bandolier'],
    ['Level 4','Get a Clean Kill After Calling to an Animal 5 Times','$10 / 50 Health XP'],
    ['Level 5','Skin Three Bears (Black or Grizzly)','$10 / 50 Health XP'],
    ['Level 6','Kill and Skin Five Cougars With Your Bow','$15 / 100 Health XP'],
    ['Level 7','Use Bait to Lure and Kill a Herbivore and a Predator','Master Hunter Gun Belt'],
    ['Level 8','Catch Three Fish Without Using a Fishing Rod','$15 / 100 Health XP'],
    ['Level 9','Catch an Opossum Playing Possum','$20 / 150 Health XP'],
    ['Level 10','Find and Kill All 16 Legendary Animals','Master Hunter Holster'],
  ],
  'SHARPSHOOTER':[
    ['Level 1','Get 10 Headshot Kills','Sharpshooter Off-Hand Holster'],
    ['Level 2','Kill 5 Flying Birds With a Varmint Rifle','$5 / 25 Dead Eye XP'],
    ['Level 3','Kill Someone 80+ Feet Away With a Throwing Knife','Sharpshooter Bandolier'],
    ['Level 4','Disarm 3 Enemies Without Killing Them','$10 / 50 Dead Eye XP'],
    ['Level 5','Kill 6 Animals Without Changing or Reloading Your Weapon','$10 / 50 Dead Eye XP'],
    ['Level 6','Shoot 3 Enemies Off Their Horses in the Same Day','$15 / 100 Dead Eye XP'],
    ['Level 7','Kill 3 Enemies in 10 Seconds Using Only a Bow','Sharpshooter Gun Belt'],
    ['Level 8','Kill 2 Different Animal Species in Same Dead Eye Activation','$15 / 100 Dead Eye XP'],
    ['Level 9','While in Dead Eye, Shoot the Hat Off a Stranger\'s Head','$20 / 150 Dead Eye XP'],
    ['Level 10','Kill 3 Flying Birds With 3 Consecutive Shots Using a Repeater','Sharpshooter Holster'],
  ],
  'SURVIVALIST':[
    ['Level 1','Craft 9 Items at Camp or in the Wild','Survivalist Off-Hand Holster'],
    ['Level 2','Craft a Potent Snake Oil','$5 / 25 Stamina XP'],
    ['Level 3','Cook a Flattened Bread Recipe','Survivalist Bandolier'],
    ['Level 4','Catch 3 Sockeye Salmon Using a Fishing Rod','$10 / 50 Stamina XP'],
    ['Level 5','Craft a Special Health Cure','$10 / 50 Stamina XP'],
    ['Level 6','Craft 3 Fire Bottles','$15 / 100 Stamina XP'],
    ['Level 7','Craft a Special Miracle Tonic','Survivalist Gun Belt'],
    ['Level 8','Craft 3 Dynamite Arrows','$15 / 100 Stamina XP'],
    ['Level 9','Craft a Potent Miracle Tonic','$20 / 150 Stamina XP'],
    ['Level 10','Craft Every Type of Arrow','Survivalist Holster'],
  ],
  'TREASURE HUNTER':[
    ['Level 1','Find a Treasure Map on a Bounty\'s Body','Treasure Hunter Off-Hand Holster'],
    ['Level 2','Find a Treasure','$5 / 25 Stamina XP'],
    ['Level 3','Find a Treasure','Treasure Hunter Bandolier'],
    ['Level 4','Complete the Jack Hall Gang Map','$10 / 50 Stamina XP'],
    ['Level 5','Complete the Poisonous Trail Map','$10 / 50 Stamina XP'],
    ['Level 6','Complete the High Stakes Map','$15 / 100 Stamina XP'],
    ['Level 7','Find a Treasure Map on a Soldier','Treasure Hunter Gun Belt'],
    ['Level 8','Complete the Landmarks of Riches Map','$15 / 100 Stamina XP'],
    ['Level 9','Find All 3 Parts of the Torn Treasure Map','$20 / 150 Stamina XP'],
    ['Level 10','Complete Jack Hall Gang, Poisonous Trail & High Stakes Maps','Treasure Hunter Holster'],
  ],
};

// STORY: {chapter: [missions]}
const ST = {
  'Prologue':['Outlaws from the West','Enter, Pursued by a Memory'],
  'Chapter 1':['A Quiet Time','Who is Not Without Sin','The Aftermath of Genesis','Old Friends','The First Shall Be Last','Blessed are the Meek?'],
  'Chapter 2':['Polite Society, Valentine Style','Due South','We Loved Once and True','The Spines of America','Americans at Rest','The First Shall Be Last','Paying a Social Call','Money Lending and Other Sins I','Money Lending and Other Sins II','A Knife Glitters in the Moonlight'],
  'Chapter 3':['Further Questions of Female Suffrage','The Fine Joys of Tobacco','Horse Flesh for Dinner','Magicians for Sport','American Distillation','An American Pastoral Scene','Advertising, the New American Art','We Loved Once and True II','Blood Feuds, Ancient and Modern','Sodom? Back to Gomorrah','A Short Walk in a Pretty Town','The Battle of Shady Belle'],
  'Chapter 4':['The Joys of Civilization','Angelo Bronte, a Man of Honor','Help a Brother Out','Horsemen, Apocalypses','Urban Pleasures','Country Pursuits','Revenge is a Dish Best Eaten','Banking, the Old American Art','The Gilded Cage','A Fine Night of Debauchery','American Fathers I','American Fathers II','The Temperance Movement','Dear Uncle Tacitus','Fatherhood and Other Dreams I','Fatherhood and Other Dreams II','No, No and Thrice, No'],
  'Chapter 5':["Of Men and Angels","Fleeting Joy","A Kind and Benevolent Gentleman","Savagery Unleashed","Hell Hath No Fury","Paradise Mercifully Departed","Dear Uncle Tacitus II","Icarus and Friends","A Fork in the Road","That's Murfree Country","Do Not Seek Absolution I","Do Not Seek Absolution II"],
  'Chapter 6':['Visiting Hours','Goodbye, Dear Friend','The Wheel','My Last Boy','Our Best Selves','Red Dead Redemption','Honor, Amongst Thieves'],
  'Epilogue I':['The Wheel','Gainful Employment','A New Future Imagined','The Tool of Trade','Welcome to the New World',"An Honest Day's Labours",'Farming, for Morons','A Bright Bouncing Boy I','A Bright Bouncing Boy II','Old Habits'],
  'Epilogue II':['The Wheel','A New Jerusalem','And the Truth Will Set You Free','Home of the Gentry?','Here Comes a New Challenger','A Really Big Bastard','American Venom'],
};

// ACHIEVEMENTS: [name, category]
const AC = [
  ['Blessed are the Peacemakers','Story'],['A Good Boy','Story'],['Gold Rush','Story'],
  ['Brothers and Sisters, One and All','Story'],['Extreme Personality','Story'],
  ['Zoologist','Exploration'],['Skin Deep','Exploration'],["Collector's Item",'Exploration'],
  ["It's Art",'Exploration'],['Paying Respects','Exploration'],['All That Glitters','Exploration'],
  ['Notorious','Exploration'],['Lending a Hand','Exploration'],['To the Victor','Exploration'],
  ["Poacher's Punt",'Combat'],['Grin and Bear It','Combat'],['Wild Kingdom','Combat'],
  ['Horseman of the Apocalypse','Combat'],['Folks From Around These Parts','Hunting'],
  ['The Veteran','Hunting'],['Outdoorsman','Hunting'],['Self Sufficient','Hunting'],
  ['Breaking and Entering','Misc'],['Trusty Steed','Honor'],['Friends with Benefits','Honor'],
  ["It's Not About the Money",'Honor'],['You Feeling Daring?','Honor'],['Trader','Honor'],
  ['Bandit for Life','Challenges'],['Explorer for Life','Challenges'],['Herbalist for Life','Challenges'],
  ['Horseman for Life','Challenges'],['Hunter for Life','Challenges'],['Master Hunter for Life','Challenges'],
  ['Sharpshooter for Life','Challenges'],['Survivalist for Life','Challenges'],['Treasure Hunter for Life','Challenges'],
  ['Redemption','Epilogue'],['A Life of Peace','Epilogue'],['Endless Summer','Epilogue'],
  ['Frontier Pursuits','Epilogue'],['Established','Epilogue'],["It Was This Big",'Misc'],
  ['Notorious Outlaw','Misc'],['Legend of the East','Misc'],['Strength in Numbers','Misc'],
  ['Brains and Brawn','Misc'],['A New Jerusalem','Misc'],['Hammer & Eagle','Misc'],
  ['Jolly Co-operation','Misc'],['Persistence Pays','Misc'],['Making Friends','Misc'],
];

// CIGARETTE CARDS: {set: {reward, cards: [[name,state,loc,desc]]}}
const CIG = {
  'Famous Gunslingers':{reward:'Special Snake Oil, $50',cards:[
    ['No. 1 Frank Heck','New Hanover','Valentine','Cemetery, base of a tombstone'],
    ['No. 2 Otis Miller Boys','New Hanover','Six Point Cabin','Wagon, to the east'],
    ['No. 3 Jack Hall Gang','Ambarino','Chez Porter','Windowsill'],
    ['No. 4 Butcher Brothers','New Hanover','Butcher Creek','Barrel (red top)'],
    ['No. 5 Flaco Hernandez','Lemoyne','Rhodes','Bank, roof'],
    ['No. 6 Slim Grant','Ambarino','Fairview Shanty','Barrel'],
    ['No. 7 Landon Ricketts','New Austin','Armadillo','House across from undertaker, out back'],
    ['No. 8 Black Belle','West Elizabeth','Blackwater','Pier, barrel'],
    ['No. 9 Billy Midnight','New Austin','Tumbleweed','Windmill'],
    ['No. 10 Emmet Granger','Lemoyne','Canebreak Manor','Barrel'],
    ["No. 11 Jim 'Boy' Calloway",'Lemoyne','Saint Denis','Graveyard, inside NW mausoleum'],
    ['No. 12 Bart Love','West Elizabeth','Hanging Dog Ranch','House, by the couch'],
  ]},
  'Artists':{reward:'Ginseng Elixir, $100',cards:[
    ['No. 1 Edith Corinne','Lemoyne','Braithwaite Manor','Central grounds, large clothesline, table'],
    ['No. 2 Elsie Rose','West Elizabeth','Strawberry','Hotel, upstairs on a table'],
    ['No. 3 W.G. Hoyt','New Hanover',"Hani's Bethel",'Table'],
    ['No. 4 Aldous Bramley','West Elizabeth','Blackwater','House south of town, porch'],
    ['No. 5 Preston T. Stephenson','New Hanover','Annesburg','Mining office, table'],
    ['No. 6 Evelyn Miller','West Elizabeth','Blackwater','Clothesline, nearby table'],
    ['No. 7 Slick Hutton','New Hanover','Van Horn Mansion','Balcony'],
    ['No. 8 Laurence Carson','Lemoyne','Saint Denis',"Trapper's market, pig alley, on a desk"],
    ['No. 9 Miss Maud Delancy','Lemoyne','Houseboat','Table'],
    ['No. 10 Charles Chatenay','New Hanover','Chadwick Farm','Porch'],
    ['No. 11 George Dixie','New Hanover','Guthrie Farm','In house on bed, next to guitar'],
    ['No. 12 Richard McCullough','Lemoyne','Saint Denis',"Near Algernon's greenhouse, patio w/ gazebo, table"],
  ]},
  'Vistas of America':{reward:'Gold Nugget, $100',cards:[
    ['No. 1 New York','Lemoyne','Caliga Hall','Row of houses, porch'],
    ['No. 2 Saint Denis','Lemoyne','Saint Denis','Train station, cart'],
    ['No. 3 Blackwater','West Elizabeth','Blackwater','Theater, roof, on a table'],
    ['No. 4 Armadillo','New Austin','Armadillo','Pig pens, barrel'],
    ['No. 5 Rio Bravo','New Hanover','Flatneck Station','Windmill'],
    ['No. 6 The Grizzlies','New Austin','Lake Don Julio','Shack'],
    ['No. 7 San Francisco','New Hanover','Fort Brennand','Tower, windowsill'],
    ['No. 8 Tall Trees','New Hanover','Flatneck Station','Outside, barrel'],
    ['No. 9 Valentine','New Hanover','Valentine','Train station'],
    ['No. 10 Chicago','New Hanover','Emerald Ranch','Windmill'],
    ['No. 11 Rhodes','Lemoyne','Rhodes','Cemetery, headstone near open grave'],
    ['No. 12 Annesburg','New Hanover','Annesburg','Elevated mining cart tracks, barrel'],
  ]},
  'Gems of Beauty':{reward:'Platinum Chain Necklace, $100',cards:[
    ['No. 1 Leila Stetson','New Hanover','Carmody Dell','Inside house, downstairs, window left of fireplace'],
    ['No. 2 Isabelle Barlow','New Hanover','Abandoned Trading Post','Shelf, inside'],
    ['No. 3 Hattie Langtry','New Hanover','Meteor House','Inside, table'],
    ['No. 4 Isabelle Standish','New Hanover','Annesburg','Inside mine (S), table'],
    ['No. 5 Maud Engel','New Hanover','Heartland Oil Fields','S of tracks, back porch, table'],
    ['No. 6 Sadie Russell','West Elizabeth','Blackwater','Chicken coop near barber, barrel'],
    ['No. 7 Geraldine Emerson','West Elizabeth','Hanging Dog Ranch','Barn, top floor, crate'],
    ['No. 8 Agnes Guyon','Ambarino','Millesani Claim','Shack, inside, box'],
    ['No. 9 Jennie Willetts','New Hanover','Van Horn','Fenced yard, barrel'],
    ['No. 10 Ilga Ulmer','Lemoyne','Saint Denis','Alley behind doctor, table'],
    ['No. 11 Fay Delaro','New Hanover','Valentine','SW barn, upper level, window'],
    ['No. 12 Pauline Henderson','New Hanover','Bacchus Station','Crate'],
  ]},
  'Flora of America':{reward:'Special Miracle Tonic, $50',cards:[
    ['No. 1 Golden Currant','Lemoyne','Lakay','Shack, shelf'],
    ['No. 2 Hummingbird Sage','New Hanover','Butcher Creek','SE of town, shack, table'],
    ['No. 3 Oleander Sage','Lemoyne','Saint Denis','Behind Rose & Oliver restaurant, up brown staircase, ledge'],
    ['No. 4 Yarrow','Lemoyne','Lakay','Cabin railing'],
    ['No. 5 Indian Tobacco','Lemoyne','Lakay','Crate to left of house'],
    ['No. 6 Black Mangrove','New Hanover','Emerald Ranch','Train station, barrel'],
    ['No. 7 Longleaf Pine','New Hanover','Annesburg','Inside mine, SW entrance, final platform'],
    ['No. 8 Desert Fan Palm','New Austin','Tumbleweed','Big house to the west, porch'],
    ['No. 9 Coastal Redwood','West Elizabeth','Strawberry','House S of town, back porch'],
    ['No. 10 Horse Crippler Cactus','Lemoyne','Caliga Hall','Workbench, shack by docks'],
    ['No. 11 Blazing Star','West Elizabeth',"Vetter's Echo",'Railing'],
    ['No. 12 Carolina Lupine','New Austin','Tumbleweed',"Sheriff's Office (not jail), roof"],
  ]},
  'Stars of the Stage':{reward:'Small Jewelry Bag, $50',cards:[
    ['No. 1 Laurence Dunn','Lemoyne','Robard Farm','Mantle'],
    ['No. 2 Louis Dunrand','New Hanover','Van Horn','House W of town, porch'],
    ['No. 3 Jesse Raymond','New Austin','Tumbleweed','Burned house to N, windowsill'],
    ['No. 4 Augusta Tremlow','West Elizabeth','Hanging Dog Ranch','Windmill'],
    ['No. 5 Mabel Potter','Lemoyne','Saint Denis','Theater, table in hallway'],
    ['No. 6 Robin Koninsky','Lemoyne','Saint Denis','Theater, wings of stage (must see 5 shows)'],
    ['No. 7 Isadore Reid','New Hanover','Valentine','Near theater tent, wagon'],
    ['No. 8 Irene Grubb','New Austin',"Macfarlane's Ranch",'Train station, bench'],
    ['No. 9 Nettie Palmer','New Hanover','Valentine','Theater tent, under projector'],
    ['No. 10 Jim Cobb','Lemoyne',"Compson's Stead",'Porch, bench'],
    ['No. 11 Mittie Comstock','New Hanover','Larned Sod','Barrel'],
    ['No. 12 Robert Elliot Patchen','Lemoyne','Rhodes','Near Fence, yellow house, crate'],
  ]},
  'Fauna of America':{reward:'Perfect Rabbit Pelt, $50',cards:[
    ['No. 1 Black Widow Spider','West Elizabeth',"Vetter's Echo",'Inside (caution: bear)'],
    ['No. 2 Bloodhound','Lemoyne','Bolger Blade','Ruined house, fireplace'],
    ['No. 3 Bluejay','New Hanover','Clingman','Viewing platform, tree'],
    ['No. 4 Catfish','Lemoyne','Saint Denis','West dock, barrel'],
    ['No. 5 Coral Snake','Lemoyne','Lakay','Fire mural on biggest house, bench'],
    ['No. 6 Grouper','Lemoyne','Lagras','Fishing boat, barrel'],
    ['No. 7 Large Mouth Bass','New Hanover',"Gill's Landing",'Under couch'],
    ['No. 8 Panther','New Hanover','Fort Brennand','Cabin, inside, crate'],
    ['No. 9 Parrot','Lemoyne',"Macomb's End",'Pier, crate'],
    ['No. 10 Pheasant','New Hanover','Clingman','Viewing platform, tree'],
    ['No. 11 Snapping Turtle','New Hanover','Firewood Rise','Under dresser'],
    ['No. 12 Turkey','New Hanover','Van Horn','Burned building, upstairs, fireplace'],
  ]},
  'Marvels of Travel':{reward:'Aged Pirate Rum, $50',cards:[
    ['No. 1 Packet Ship','New Hanover','Annesburg','Dock, under roofed area, crate'],
    ['No. 2 Schooner','New Hanover','Van Horn','Houseboat, under bed'],
    ['No. 3 Camel Caravan','Lemoyne','Rhodes','Near saloon, clothesline table'],
    ['No. 4 Elephant Carriage','West Elizabeth','Strawberry',"Tracker's Hotel, rear staircase, railing"],
    ['No. 5 Goat Carriage','New Hanover','Emerald Ranch','Stables, workbench'],
    ['No. 6 Hot Air Balloon','Lemoyne','Saint Denis','Saloon (E), shelf'],
    ['No. 7 U.S. Frigate','Lemoyne','Braithwaite Manor','Near docks, workshop with boat, table'],
    ['No. 8 The Showboat','Lemoyne','Saint Denis','Pier (S), fish-gutting table'],
    ['No. 9 Balener Whaling Vessel','Lemoyne','Saint Denis','Docks, blue octagonal building, sill'],
    ['No. 10 Stagecoach','West Elizabeth','Riggs Station','Bench'],
    ['No. 11 Steam Locomotive II','Lemoyne','Clemens Point','Wall, ruined house to north'],
    ['No. 12 Velocipede','Lemoyne','Saint Denis','Big fancy green house E of Mayor, W side porch, table'],
  ]},
  'World Champions':{reward:'Valerian Root, $50',cards:[
    ['No. 1 Percy Wood','New Hanover','Butcher Creek','Shack S of town, nearby well'],
    ['No. 2 Edwin A. Rowe','New Hanover',"Clawson's Rest",'Windowsill'],
    ['No. 3 Theobald Getzin','New Hanover','Emerald Ranch','House to N, shelf'],
    ['No. 4 H.T. Solcum','Lemoyne','Canebreak Manor','Under shack, box'],
    ['No. 5 Felix Hawley','New Hanover',"Maclean's House",'Side of house, table'],
    ['No. 6 Patsey Hill','Lemoyne','Trail Rise','Basement, shelf'],
    ['No. 7 R.S. Harradon','Lemoyne','Saint Denis','House E of graveyard, back porch, planks railing'],
    ['No. 8 William Sleicher','New Hanover','Heartland Oil Fields','S of tracks, back porch, table'],
    ['No. 9 E.D. Ewing "Walker"','New Hanover','Annesburg','Mining tower'],
    ['No. 10 Edwin Singerly','Ambarino','Barrow Lagoon','Cabin, inside, table'],
    ['No. 11 Capt. Jack Page','New Hanover',"Clawson's Rest",'Windowsill'],
    ['No. 12 Axel McCormack','Lemoyne','Saint Denis','Saloon (W), rear courtyard, crate'],
  ]},
  'Amazing Inventions':{reward:'Volatile Dynamite, $100',cards:[
    ['No. 1 Steam Locomotive','Lemoyne','Bolger Blade','Ruined church, upper level, bird nest on ledge'],
    ['No. 2 Camera','Lemoyne','Saint Denis','Near photo studio, balcony'],
    ['No. 3 Electrical Execution','West Elizabeth','Hanging Dog Ranch','House, under bunk beds'],
    ['No. 4 Typewriter','West Elizabeth','Blackwater','Warehouse W of post office, corner next to ramp, barrel'],
    ['No. 5 Revolver','New Hanover','Annesburg','Gunsmith, out back, table'],
    ['No. 6 Telegraph','New Hanover','Van Horn','Train station, bench'],
    ['No. 7 Manned Glider','Lemoyne','Caliga Hall','Barn, inside on bench'],
    ['No. 8 Dynamite','Lemoyne','Shady Belle','Porch'],
    ['No. 9 Cylinder Phonograph','New Hanover','Valentine','Saloon, windowsill'],
    ['No. 10 Player Piano','Lemoyne','Saint Denis','Saloon (W), piano'],
    ['No. 11 Electric Lightbulb','New Hanover','Doverhill','Rear door, box'],
    ['No. 12 Telephone','New Hanover','Annesburg','Mine interior, final chamber, table'],
  ]},
  'Historical Figures':{reward:'Special Bitters, $100',cards:[
    ['No. 1 Abraham Lincoln','Lemoyne','Saint Denis','Hotel (W), lobby, shelf by clock'],
    ['No. 2 Albert Einstein','New Hanover','Emerald Ranch','Train station, on a bench'],
    ['No. 3 Calamity Jane','West Elizabeth','Blackwater','Hotel, upstairs, table'],
    ['No. 4 Charles Darwin','Lemoyne','Saint Denis','Museum of Art, lower level, table'],
    ['No. 5 Frederick Douglass','Lemoyne','Saint Denis','Warehouse off the docks, box'],
    ['No. 6 Geronimo','New Hanover','Van Horn','Ruined building, crate'],
    ['No. 7 Harriet Tubman','New Hanover','Annesburg','Church, inside, pew'],
    ['No. 8 Jesse James','New Hanover','Flatneck Station','Train station platform, barrel'],
    ['No. 9 Mark Twain','New Hanover','Emerald Ranch','House to the north, shelf'],
    ['No. 10 Nikola Tesla','West Elizabeth','Blackwater','Power station, table'],
    ['No. 11 P.T. Barnum','New Hanover','Valentine','Stable roof, barrel'],
    ['No. 12 Sitting Bull','Ambarino','Wapiti Indian Reservation','Large building, on a table'],
  ]},
  'Anatomy of the Horse':{reward:'Horse Stimulant, $50',cards:[
    ['No. 1 The Frame','New Hanover','Heartland Oil Fields','N of tracks, house to the right, shelf'],
    ['No. 2 The Muscular System','New Hanover','Annesburg','Mining company office, shelf'],
    ['No. 3 The Dental System','New Hanover','Van Horn','Burned building remains, box'],
    ['No. 4 The Digestive System','Lemoyne','Caliga Hall','Row of houses, inside one, shelf'],
    ['No. 5 The Respiratory System','West Elizabeth','Blackwater','Stable, hay bale'],
    ['No. 6 The Circulatory System','New Hanover','Chadwick Farm','Inside house, table'],
    ["No. 7 The Nervous System",'West Elizabeth','Strawberry',"Doctor's office, shelf"],
    ['No. 8 The Integumentary System','New Hanover','Valentine','Post office, box in corner'],
    ['No. 9 The Reproductive System','West Elizabeth','Hanging Dog Ranch','Inside barn, crate near horse stall'],
    ['No. 10 The Immune System','New Hanover','Annesburg','Near mineshaft entrance, barrel'],
    ['No. 11 Locomotion I','Lemoyne','Lagras','Shack to the southeast, shelf'],
    ['No. 12 Locomotion II','New Hanover','Butcher Creek','Ruined building, fireplace mantle'],
  ]},
};
